//! Build script for simply-daemon.
//!
//! Pipeline:
//! 1. Parse src/api/*.rs for #[rpc_service] traits
//! 2. Generate TypeScript API client → admin/src/lib/generated/api.ts
//!    (Types are generated by ts-rs via `cargo test ts_export`)
//! 3. npm install + npm run build → admin/dist/
//!
//! Set SKIP_ADMIN_BUILD=1 to skip everything (fast Rust-only iteration).

use std::path::PathBuf;
use std::process::Command;
use std::fs;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    // Watch each .rs file individually — `rerun-if-changed=api/src/` only tracks
    // the directory mtime, which doesn't change on file edits.
    if let Ok(entries) = glob::glob("api/src/**/*.rs") {
        for entry in entries.flatten() {
            println!("cargo:rerun-if-changed={}", entry.display());
        }
    }

    if std::env::var("SKIP_ADMIN_BUILD").is_ok() {
        return;
    }

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let api_dir = manifest_dir.join("api/src");
    let admin_dir = manifest_dir.join("admin");
    let generated_dir = admin_dir.join("src/lib/generated");

    // Step 1: Generate API client + types barrel
    if api_dir.is_dir() && admin_dir.join("package.json").exists() {
        fs::create_dir_all(&generated_dir).ok();
        fs::create_dir_all(generated_dir.join("types")).ok();
        generate_api_client(&api_dir, &generated_dir);
        generate_types_barrel(&generated_dir);
    }

    // Step 2: Build admin UI
    if admin_dir.join("package.json").exists() {
        // npm install if needed
        if !admin_dir.join("node_modules").exists() {
            run_or_panic("npm", &["install"], &admin_dir, "npm install failed");
        }
        // npm run build
        run_or_panic("npm", &["run", "build"], &admin_dir, "admin UI build failed");
    }
}

fn run_or_panic(cmd: &str, args: &[&str], dir: &PathBuf, msg: &str) {
    match Command::new(cmd).args(args).current_dir(dir).status() {
        Ok(s) if s.success() => {}
        Ok(s) => panic!("{msg}: {s}"),
        Err(e) => panic!("{msg}: {e}"),
    }
}

// ---------------------------------------------------------------------------
// API client generation (types come from ts-rs)
// ---------------------------------------------------------------------------

/// Known types that serialize as plain strings (ID newtypes, etc.)
const STRING_TYPES: &[&str] = &[
    "SessionId", "ConversationId", "DocumentId", "AssetId", "BlobHash",
    "TabId", "TurnId", "SpanId", "EntityId", "UserId", "RevisionId",
    "ChunkId", "CollectionId",
];

/// Parameter types handled by the transport layer, not the client.
/// These are stripped from generated TS function signatures.
const TRANSPORT_PARAMS: &[&str] = &["RequestContext", "BinaryUpload"];

fn generate_api_client(api_dir: &PathBuf, out_dir: &PathBuf) {
    let pattern = format!("{}/**/*.rs", api_dir.display());
    let files: Vec<_> = glob::glob(&pattern)
        .unwrap()
        .filter_map(|r| r.ok())
        .collect();

    let mut client = String::new();
    let mut service_count = 0;

    client.push_str("// Auto-generated TypeScript API clients from #[rpc_service] traits.\n");
    client.push_str("// Do not edit — regenerated by simply-daemon build.rs\n");
    client.push_str("// Types are generated separately by ts-rs.\n\n");
    client.push_str("import type { Transport } from '../transport';\n");
    client.push_str("import type * as T from './types';\n\n");

    for file in &files {
        let source = match fs::read_to_string(file) {
            Ok(s) => s,
            Err(_) => continue,
        };

        let syntax = match syn::parse_file(&source) {
            Ok(f) => f,
            Err(e) => {
                println!("cargo:warning=Failed to parse {}: {e}", file.display());
                continue;
            }
        };

        for item in &syntax.items {
            if let syn::Item::Trait(t) = item {
                if let Some(prefix) = extract_rpc_service_prefix(&t.attrs) {
                    client.push_str(&generate_service_client(&prefix, t));
                    client.push('\n');
                    service_count += 1;
                }
            }
        }
    }

    fs::write(out_dir.join("api.ts"), &client).expect("failed to write api.ts");

    // Generate index.ts barrel
    let mut index = String::from("// Auto-generated barrel export\n");
    index.push_str("export * from './types';\n");
    index.push_str("export * from './api';\n");
    fs::write(out_dir.join("index.ts"), &index).expect("failed to write index.ts");

    println!(
        "cargo:warning=Generated {service_count} API clients → {}",
        out_dir.display()
    );
}

/// Scan `types/` for ts-rs generated `.ts` files and create a barrel `types.ts`
/// that re-exports everything. If no files exist yet (ts-rs test hasn't run),
/// leaves `types.ts` as-is.
fn generate_types_barrel(out_dir: &PathBuf) {
    let types_dir = out_dir.join("types");
    if !types_dir.is_dir() { return; }

    let pattern = format!("{}/*.ts", types_dir.display());
    let files: Vec<_> = glob::glob(&pattern)
        .unwrap()
        .filter_map(|r| r.ok())
        .filter(|p| {
            let name = p.file_name().unwrap().to_string_lossy();
            name != "index.ts" // don't re-export self
        })
        .collect();

    if files.is_empty() { return; }

    let mut barrel = String::from("// Auto-generated barrel — re-exports all ts-rs type files.\n");
    barrel.push_str("// Do not edit — regenerated by simply-daemon build.rs\n\n");

    for file in &files {
        let stem = file.file_stem().unwrap().to_string_lossy();
        barrel.push_str(&format!("export * from './types/{stem}';\n"));
    }

    let type_count = files.len();
    fs::write(out_dir.join("types.ts"), &barrel).expect("failed to write types.ts barrel");

    println!(
        "cargo:warning=Generated types barrel with {type_count} type files → {}",
        out_dir.join("types.ts").display()
    );
}

fn has_derive(attrs: &[syn::Attribute], name: &str) -> bool {
    attrs.iter().any(|attr| {
        if !attr.path().is_ident("derive") { return false; }
        attr.meta.require_list()
            .map(|list| list.tokens.to_string().contains(name))
            .unwrap_or(false)
    })
}

// ---------------------------------------------------------------------------
// Trait → TypeScript API client
// ---------------------------------------------------------------------------

fn extract_rpc_service_prefix(attrs: &[syn::Attribute]) -> Option<String> {
    for attr in attrs {
        let path = attr.path();
        let is_rpc = path.is_ident("rpc_service")
            || path.segments.iter().any(|s| s.ident == "rpc_service");
        if !is_rpc { continue; }
        if let syn::Meta::List(list) = &attr.meta {
            let tokens = list.tokens.to_string();
            let prefix = tokens.trim().trim_matches('"').to_string();
            if !prefix.is_empty() { return Some(prefix); }
        }
    }
    None
}

fn generate_service_client(prefix: &str, trait_item: &syn::ItemTrait) -> String {
    let trait_name = trait_item.ident.to_string();
    let mut out = String::new();

    out.push_str(&format!("// {trait_name}\n"));
    out.push_str(&format!(
        "export const {} = (t: Transport) => ({{\n",
        to_camel_case(&trait_name)
    ));

    for item in &trait_item.items {
        let syn::TraitItem::Fn(method) = item else { continue };

        let Some((http_method, path_template)) = extract_rpc_route(&method.attrs) else {
            continue;
        };
        if http_method == "STREAM" { continue; }

        let method_name = method.sig.ident.to_string();
        let doc = extract_doc_comment(&method.attrs);
        let params = parse_method_params(&method.sig);
        let path_params = extract_path_params(&path_template);
        let return_type = parse_return_type_ts(&method.sig.output);

        let mut ts_params = Vec::new();
        let mut body_params = Vec::new();

        for (name, ty) in &params {
            // Skip params handled by the transport layer (e.g. RequestContext → header)
            let bare_type = ty.rsplit("::").next().unwrap_or(ty).trim_start_matches('&');
            if TRANSPORT_PARAMS.contains(&bare_type) { continue; }

            let ts_type = rust_type_to_ts_from_str(ty);
            ts_params.push(format!("{}: {ts_type}", to_camel_case(name)));
            if !path_params.contains(name) {
                body_params.push(to_camel_case(name));
            }
        }

        let params_str = ts_params.join(", ");
        let url = build_ts_url(prefix, &path_template, &path_params);

        let body = if body_params.is_empty() {
            None
        } else if body_params.len() == 1 && path_params.is_empty() {
            // Single body param, no path params → send directly
            Some(body_params[0].clone())
        } else {
            // Mix of path + body params → wrap body params in object
            Some(format!("{{ {} }}", body_params.join(", ")))
        };

        if let Some(ref doc) = doc {
            out.push_str(&format!("  /** {doc} */\n"));
        }

        let fn_name = to_camel_case(&method_name);
        let rpc_name = format!("{prefix}.{method_name}");
        match body {
            None => out.push_str(&format!(
                "  {fn_name}: ({params_str}) => t.rpc<{return_type}>('{rpc_name}', '{http_method}', {url}),\n"
            )),
            Some(b) => out.push_str(&format!(
                "  {fn_name}: ({params_str}) => t.rpc<{return_type}>('{rpc_name}', '{http_method}', {url}, {b}),\n"
            )),
        }
    }

    out.push_str("});\n");
    out
}

fn extract_rpc_route(attrs: &[syn::Attribute]) -> Option<(String, String)> {
    for attr in attrs {
        if !attr.path().is_ident("rpc") { continue; }
        let syn::Meta::List(list) = &attr.meta else { continue };
        let tokens = list.tokens.to_string().replace(' ', "");
        if tokens.contains("skip") { return None; }
        for method in &["get", "post", "put", "delete", "stream"] {
            if let Some(rest) = tokens.strip_prefix(&format!("{method}=")) {
                let path = rest.split(',').next().unwrap_or(rest).trim_matches('"');
                let http = if *method == "stream" { "STREAM".into() } else { method.to_uppercase() };
                return Some((http, path.to_string()));
            }
        }
    }
    None
}

fn extract_doc_comment(attrs: &[syn::Attribute]) -> Option<String> {
    let lines: Vec<String> = attrs.iter().filter_map(|attr| {
        if !attr.path().is_ident("doc") { return None; }
        if let syn::Meta::NameValue(nv) = &attr.meta {
            if let syn::Expr::Lit(lit) = &nv.value {
                if let syn::Lit::Str(s) = &lit.lit {
                    return Some(s.value().trim().to_string());
                }
            }
        }
        None
    }).collect();
    if lines.is_empty() { None } else { Some(lines.join(" ")) }
}

fn parse_method_params(sig: &syn::Signature) -> Vec<(String, String)> {
    sig.inputs.iter().filter_map(|arg| {
        let syn::FnArg::Typed(pat_type) = arg else { return None };
        let syn::Pat::Ident(pat_ident) = pat_type.pat.as_ref() else { return None };
        let name = pat_ident.ident.to_string();
        let ty_ref = &pat_type.ty;
        let ty = quote::quote!(#ty_ref).to_string().replace(' ', "");
        Some((name, ty))
    }).collect()
}

fn parse_return_type_ts(output: &syn::ReturnType) -> String {
    let syn::ReturnType::Type(_, ty) = output else { return "void".to_string() };
    let s = quote::quote!(#ty).to_string().replace(' ', "");
    let inner = extract_generic_inner(&s, "Result").unwrap_or(s);
    if inner == "()" { return "void".to_string(); }
    rust_type_to_ts_from_str(&inner)
}

fn extract_generic_inner(s: &str, wrapper: &str) -> Option<String> {
    let needle = format!("{wrapper}<");
    let start = s.find(&needle)?;
    let rest = &s[start + needle.len()..];
    let mut depth = 1;
    for (i, c) in rest.char_indices() {
        match c {
            '<' => depth += 1,
            '>' => { depth -= 1; if depth == 0 { return Some(rest[..i].to_string()); } }
            _ => {}
        }
    }
    None
}

fn extract_path_params(path: &str) -> Vec<String> {
    let mut params = Vec::new();
    let mut rest = path;
    while let Some(start) = rest.find('{') {
        if let Some(end) = rest[start..].find('}') {
            params.push(rest[start + 1..start + end].to_string());
            rest = &rest[start + end + 1..];
        } else { break; }
    }
    params
}

fn build_ts_url(prefix: &str, template: &str, path_params: &[String]) -> String {
    if path_params.is_empty() {
        format!("'/api{template}'")
    } else {
        let mut url = format!("/api{template}");
        for param in path_params {
            let camel = to_camel_case(param);
            url = url.replace(&format!("{{{param}}}"), &format!("${{{camel}}}"));
        }
        format!("`{url}`")
    }
}

// ---------------------------------------------------------------------------
// Type conversion
// ---------------------------------------------------------------------------

fn rust_type_to_ts_from_str(s: &str) -> String {
    // Strip leading & for references
    let s = s.strip_prefix('&').unwrap_or(s);

    match s {
        "String" | "str" => return "string".to_string(),
        "bool" => return "boolean".to_string(),
        "i32" | "i64" | "u32" | "u64" | "usize" | "isize" | "f32" | "f64" => return "number".to_string(),
        "()" => return "void".to_string(),
        _ => {}
    }

    if let Some(inner) = extract_generic_inner(s, "Vec") {
        return format!("{}[]", rust_type_to_ts_from_str(&inner));
    }
    if let Some(inner) = extract_generic_inner(s, "Option") {
        return format!("{} | null", rust_type_to_ts_from_str(&inner));
    }

    // Check if it's a known string-serialized ID type
    let name = s.rsplit("::").next().unwrap_or(s);
    if STRING_TYPES.contains(&name) {
        return "string".to_string();
    }

    // Complex type — reference from ts-rs generated types
    format!("T.{name}")
}

fn to_camel_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = false;
    for (i, c) in s.chars().enumerate() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_uppercase().next().unwrap());
            capitalize_next = false;
        } else if i == 0 {
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }
    result
}
