[package]
name = "simply-audio"
version.workspace = true
edition.workspace = true

[features]
default = []
backend-cpal = ["dep:cpal"]
browser = []

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
cpal = { version = "0.16.0", optional = true }
dirs = { workspace = true }
llm = { workspace = true }
simply-core = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
whisper-rs = "0.15.1"
