// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fork result containing both conversation and thread IDs
 */
export type ForkResult = { conversation_id: string, thread_id: string, };
