[package]
name = "simply-rpc"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1"
async-trait = "0.1"
base64 = "0.22"
matchit = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simply-rpc-macros = { path = "macros" }

[dev-dependencies]
tokio = { version = "1", features = ["full", "sync"] }
reqwest = { version = "0.12", features = ["json"] }
hyper = { version = "1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
http-body-util = "0.1"
tokio-tungstenite = "0.26"
futures-util = "0.3"
