//! Entity types for the addressable layer
//!
//! All addressable things (conversations, documents, notes, directories, labels)
//! are entities with:
//! - Unified identity (id, type, name, slug)
//! - Consistent metadata (user, privacy, archive status)
//! - At-most-one content block (`content_block_id`)
//! - Optional URI-like origin (`"<scheme>:<id>"`)
//! - Relationships via `entity_relations`

use serde::{Deserialize, Serialize};

use crate::storage::ids::{ContentBlockId, UserId};

// ============================================================================
// EntityType
// ============================================================================

/// Type of entity in the addressable layer
///
/// Stored as a namespaced string for extensibility — new entity types can be
/// added without code changes. The frontend dispatches on this value to
/// determine how to render and what domain-specific data to fetch.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct EntityType(String);

impl EntityType {
    /// Create a new entity type
    pub fn new(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    /// Get the string value
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Does this type belong to the `document::` namespace?
    /// Used by RAG default filters and admin UI grouping.
    pub fn is_document_like(&self) -> bool {
        self.0.starts_with("document::")
    }

    // ----- Well-known top-level entity types -----
    //
    // Document subkinds (`document::note`, `::tabbed`, `::tab`, ...) and
    // system organizational primitives (`system::directory`, `system::label`)
    // are *not* enumerated here. Clients (admin UI, Noema UI, import skills)
    // own their own lists of kinds and pass strings directly via
    // `EntityType::new("document::whatever")`. Keeps the daemon from needing
    // to ship a new constant every time a client wants a new flavour.

    /// Conversation entity (a view + turns + spans + messages).
    /// First-class daemon concept — owned by `SessionManager`.
    pub fn conversation() -> Self {
        Self::new("conversation")
    }
}

impl std::fmt::Display for EntityType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl From<&str> for EntityType {
    fn from(s: &str) -> Self {
        Self::new(s)
    }
}

impl From<String> for EntityType {
    fn from(s: String) -> Self {
        Self(s)
    }
}

// ============================================================================
// Origin
// ============================================================================

/// Well-known `origin` scheme strings. The `origin` column on `entities`
/// holds `"<scheme>:<id>"` values like `"google_drive:gdoc-abc123"`.
/// Schemes are not a closed set — new ones can be introduced freely.
pub mod origin_scheme {
    /// Imported from Google Drive / Docs.
    pub const GOOGLE_DRIVE: &str = "google_drive";
    /// Generated by the AI / assistant.
    pub const AI_GENERATED: &str = "ai_generated";
    /// Captured from a browser tab (future chrome extension).
    pub const BROWSER: &str = "browser";
}

/// Build an origin string from a scheme and id.
pub fn origin(scheme: &str, id: &str) -> String {
    format!("{scheme}:{id}")
}

/// Split an origin string into `(scheme, id)`. Returns `None` if the string
/// has no `:` separator.
pub fn parse_origin(s: &str) -> Option<(&str, &str)> {
    s.split_once(':')
}

// ============================================================================
// Entity
// ============================================================================

/// Core entity data for the addressable layer
///
/// Entities provide unified identity, content linkage, and metadata for all
/// addressable things. Domain-specific structure (tab trees, revision history)
/// emerges from `entity_relations` rather than from dedicated tables.
///
/// Use with `StoredEditable<EntityId, Entity>` for the full stored representation.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Entity {
    /// Type of entity (extensible string, e.g., `"conversation"`, `"document::tabbed"`)
    pub entity_type: EntityType,
    /// Owning user (optional for shared entities)
    pub user_id: Option<UserId>,
    /// Human-readable display name. @mentions resolve to entity_id via name lookup;
    /// the stored reference is a structured ref (entity_id), not a string.
    pub name: Option<String>,
    /// Whether content is private (local-only, never sent to cloud)
    pub is_private: bool,
    /// At most one content block holds the entity's live markdown text.
    pub content_block_id: Option<ContentBlockId>,
    /// URI-like origin string `"<scheme>:<id>"` (e.g. `"google_drive:gdoc-abc123"`).
    /// `None` = locally authored with no external source.
    pub origin: Option<String>,
    /// Type-specific metadata as JSON (icon, etc.)
    pub metadata: Option<serde_json::Value>,
}

impl Entity {
    /// Create a new entity of the given type
    pub fn new(entity_type: EntityType) -> Self {
        Self {
            entity_type,
            user_id: None,
            name: None,
            is_private: true,
            content_block_id: None,
            origin: None,
            metadata: None,
        }
    }

    /// Set the owning user
    pub fn with_user(mut self, user_id: UserId) -> Self {
        self.user_id = Some(user_id);
        self
    }

    /// Set the display name
    pub fn with_name(mut self, name: impl Into<String>) -> Self {
        self.name = Some(name.into());
        self
    }

    /// Mark as public (content can be sent to cloud models)
    pub fn public(mut self) -> Self {
        self.is_private = false;
        self
    }

    /// Set the live content block id
    pub fn with_content_block(mut self, content_block_id: ContentBlockId) -> Self {
        self.content_block_id = Some(content_block_id);
        self
    }

    /// Set the origin string (usually built via [`origin`])
    pub fn with_origin(mut self, origin: impl Into<String>) -> Self {
        self.origin = Some(origin.into());
        self
    }

    /// Set type-specific metadata
    pub fn with_metadata(mut self, metadata: serde_json::Value) -> Self {
        self.metadata = Some(metadata);
        self
    }
}

// ============================================================================
// EntityRangeQuery
// ============================================================================

/// Query parameters for time-range entity search
///
/// Used with `EntityStore::list_entities_in_range`.
#[derive(Clone, Debug, Default)]
pub struct EntityRangeQuery {
    /// Start of time range (unix timestamp ms, inclusive)
    pub start: i64,
    /// End of time range (unix timestamp ms, inclusive)
    pub end: i64,
    /// Filter to specific entity types (None = all types)
    pub entity_types: Option<Vec<EntityType>>,
    /// Maximum number of results (None = no limit)
    pub limit: Option<u32>,
}

impl EntityRangeQuery {
    /// Create a new query for a time range
    pub fn new(start: i64, end: i64) -> Self {
        Self {
            start,
            end,
            entity_types: None,
            limit: None,
        }
    }

    /// Filter to specific entity types
    pub fn with_types(mut self, types: impl IntoIterator<Item = EntityType>) -> Self {
        self.entity_types = Some(types.into_iter().collect());
        self
    }

    /// Limit number of results
    pub fn with_limit(mut self, limit: u32) -> Self {
        self.limit = Some(limit);
        self
    }

    /// Get entity types as slice (for query)
    pub fn types_slice(&self) -> Option<&[EntityType]> {
        self.entity_types.as_deref()
    }
}

// ============================================================================
// RelationType
// ============================================================================

/// Type of relationship between entities
///
/// Namespaced as `<namespace>::<name>` for consistency with `EntityType`. New
/// relation types can be added without code changes.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct RelationType(String);

impl RelationType {
    /// Create a new relation type
    pub fn new(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    /// Get the string value
    pub fn as_str(&self) -> &str {
        &self.0
    }

    // ----- Well-known relation types -----

    /// `structure::contained_in` — child lives inside parent.
    /// Used for tabs-in-docs and files-in-directories; `position` orders siblings.
    pub fn structure_contained_in() -> Self {
        Self::new("structure::contained_in")
    }

    /// `reference::to` — A has a cross-reference to B.
    /// Generic cross-reference / knowledge-graph edge.
    pub fn reference_to() -> Self {
        Self::new("reference::to")
    }

    /// `reference::cites` — A cites B (citation-specific variant of reference).
    pub fn reference_cites() -> Self {
        Self::new("reference::cites")
    }

    /// `reference::mentions` — A @-mentions B in its content.
    pub fn reference_mentions() -> Self {
        Self::new("reference::mentions")
    }

    /// `label::tagged_with` — entity is tagged with a label.
    pub fn label_tagged_with() -> Self {
        Self::new("label::tagged_with")
    }

    /// `conversation::forked_from` — view forked from another view.
    /// Metadata: `{at_turn_id}`.
    pub fn conversation_forked_from() -> Self {
        Self::new("conversation::forked_from")
    }

    /// `conversation::spawned_from` — subconversation spawned from parent.
    /// Metadata: `{at_turn_id, at_span_id}`.
    pub fn conversation_spawned_from() -> Self {
        Self::new("conversation::spawned_from")
    }

    /// `collection::grouped_with` — manual grouping / collection membership.
    pub fn collection_grouped_with() -> Self {
        Self::new("collection::grouped_with")
    }
}

impl std::fmt::Display for RelationType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl From<&str> for RelationType {
    fn from(s: &str) -> Self {
        Self::new(s)
    }
}

impl From<String> for RelationType {
    fn from(s: String) -> Self {
        Self(s)
    }
}

// ============================================================================
// EntityRelation
// ============================================================================

/// A relationship between two entities
///
/// Relations are directional: `from_id` relates to `to_id`. Optional `position`
/// gives sibling ordering (e.g. tab_index) first-class support. Optional
/// `metadata` carries relation-specific extras (fork-point, citation context).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct EntityRelation {
    /// Type of relationship
    pub relation: RelationType,
    /// Optional ordering across siblings sharing the same `(to_id, relation)`.
    /// `None` for unordered relations (e.g. references, tagged_with).
    pub position: Option<i64>,
    /// Optional JSON metadata (e.g., `{at_turn_id: "..."}` for forks)
    pub metadata: Option<serde_json::Value>,
}

impl EntityRelation {
    /// Create a new relation
    pub fn new(relation: RelationType) -> Self {
        Self {
            relation,
            position: None,
            metadata: None,
        }
    }

    /// Add an ordering position to the relation
    pub fn with_position(mut self, position: i64) -> Self {
        self.position = Some(position);
        self
    }

    /// Add metadata to the relation
    pub fn with_metadata(mut self, metadata: serde_json::Value) -> Self {
        self.metadata = Some(metadata);
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_entity_type_conversation() {
        assert_eq!(EntityType::conversation().as_str(), "conversation");
    }

    #[test]
    fn test_entity_type_custom() {
        let custom = EntityType::new("document::note");
        assert_eq!(custom.as_str(), "document::note");
    }

    #[test]
    fn test_is_document_like() {
        assert!(EntityType::new("document::tabbed").is_document_like());
        assert!(EntityType::new("document::note").is_document_like());
        assert!(EntityType::new("document::tab").is_document_like());
        assert!(!EntityType::conversation().is_document_like());
        assert!(!EntityType::new("system::directory").is_document_like());
    }

    #[test]
    fn test_relation_type_wellknown() {
        assert_eq!(
            RelationType::structure_contained_in().as_str(),
            "structure::contained_in"
        );
        assert_eq!(RelationType::reference_to().as_str(), "reference::to");
        assert_eq!(
            RelationType::reference_cites().as_str(),
            "reference::cites"
        );
        assert_eq!(
            RelationType::reference_mentions().as_str(),
            "reference::mentions"
        );
        assert_eq!(
            RelationType::label_tagged_with().as_str(),
            "label::tagged_with"
        );
        assert_eq!(
            RelationType::conversation_forked_from().as_str(),
            "conversation::forked_from"
        );
        assert_eq!(
            RelationType::conversation_spawned_from().as_str(),
            "conversation::spawned_from"
        );
        assert_eq!(
            RelationType::collection_grouped_with().as_str(),
            "collection::grouped_with"
        );
    }

    #[test]
    fn test_origin_helpers() {
        let o = origin(origin_scheme::GOOGLE_DRIVE, "gdoc-abc123");
        assert_eq!(o, "google_drive:gdoc-abc123");
        let (scheme, id) = parse_origin(&o).unwrap();
        assert_eq!(scheme, "google_drive");
        assert_eq!(id, "gdoc-abc123");
        assert!(parse_origin("no_colon_here").is_none());
    }

    #[test]
    fn test_entity_builder() {
        let entity = Entity::new(EntityType::conversation())
            .with_user(UserId::from_string("user-1"))
            .with_name("My Conversation")
            .public();

        assert_eq!(entity.entity_type.as_str(), "conversation");
        assert_eq!(entity.user_id.as_ref().map(|u| u.as_str()), Some("user-1"));
        assert_eq!(entity.name.as_deref(), Some("My Conversation"));
        assert!(!entity.is_private);
        assert!(entity.content_block_id.is_none());
        assert!(entity.origin.is_none());
    }

    #[test]
    fn test_entity_with_content_and_origin() {
        let block_id = ContentBlockId::from_string("cb-1");
        let entity = Entity::new(EntityType::new("document::tabbed"))
            .with_content_block(block_id.clone())
            .with_origin(origin(origin_scheme::GOOGLE_DRIVE, "gdoc-abc"));
        assert_eq!(entity.content_block_id.as_ref(), Some(&block_id));
        assert_eq!(entity.origin.as_deref(), Some("google_drive:gdoc-abc"));
    }

    #[test]
    fn test_entity_defaults() {
        let entity = Entity::new(EntityType::document_note());

        assert!(entity.is_private); // Private by default
        assert!(entity.name.is_none());
        assert!(entity.user_id.is_none());
    }

    #[test]
    fn test_relation_with_metadata_and_position() {
        let metadata = serde_json::json!({
            "at_turn_id": "turn-123"
        });

        let relation = EntityRelation::new(RelationType::conversation_forked_from())
            .with_metadata(metadata.clone())
            .with_position(3);

        assert_eq!(
            relation.relation.as_str(),
            "conversation::forked_from"
        );
        assert_eq!(relation.metadata, Some(metadata));
        assert_eq!(relation.position, Some(3));
    }
}
