[package]
name = "commands"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
commands_macros = { workspace = true }

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
