//! RemoteDaemon — implements `Daemon` by composing generated remote API clients.
//!
//! Each API trait gets a `RemoteXxxApi` struct (generated by the macro) that
//! holds an `Arc<dyn RpcConnection>`. RemoteDaemon creates one per API trait
//! and delegates through the `Daemon` trait.

use std::sync::Arc;

use async_trait::async_trait;
use simply_rpc::RpcConnection;
use simply_rpc::ws_client::ConnectionState;
use tokio::sync::watch;

use crate::*;
use crate::client::DaemonRpcConnection;

/// A daemon client that talks to a remote daemon over REST + WebSocket.
pub struct RemoteDaemon {
    conn: Arc<DaemonRpcConnection>,
    session: RemoteSessionApi,
    conversation: RemoteConversationApi,
    asset: RemoteAssetApi,
    document: RemoteDocumentApi,
    mcp: RemoteMcpApi,
    oauth: RemoteOAuthApi,
    model: RemoteModelApi,
    voice: RemoteVoiceApi,
    core: RemoteCoreApi,
    search: RemoteSearchApi,
    user: RemoteUserApi,
}

impl RemoteDaemon {
    pub async fn connect_as(addr: &str, name: &str, daemon_secret: &str, user_id: Option<&str>) -> anyhow::Result<Arc<Self>> {
        let conn = Arc::new(DaemonRpcConnection::connect(addr, name, daemon_secret, user_id).await?);
        let rpc: Arc<dyn RpcConnection> = conn.clone();

        Ok(Arc::new(Self {
            session: RemoteSessionApi::new(rpc.clone()),
            conversation: RemoteConversationApi::new(rpc.clone()),
            asset: RemoteAssetApi::new(rpc.clone()),
            document: RemoteDocumentApi::new(rpc.clone()),
            mcp: RemoteMcpApi::new(rpc.clone()),
            oauth: RemoteOAuthApi::new(rpc.clone()),
            model: RemoteModelApi::new(rpc.clone()),
            voice: RemoteVoiceApi::new(rpc.clone()),
            core: RemoteCoreApi::new(rpc.clone()),
            search: RemoteSearchApi::new(rpc.clone()),
            user: RemoteUserApi::new(rpc),
            conn,
        }))
    }

    // TODO: register_tools() — send tools.register over WS, handle reverse calls.
    // Needs WsConnection to support:
    // 1. write_tx() to get a write channel for sending responses
    // 2. on_reverse_call() to handle incoming requests from the server
    // See simply-daemon/src/services/ws_tools.rs for the server-side protocol.

    pub fn connection_state(&self) -> ConnectionState {
        self.conn.connection_state()
    }

    pub fn watch_connection_state(&self) -> watch::Receiver<ConnectionState> {
        self.conn.watch_state()
    }
}

impl Daemon for RemoteDaemon {
    fn session(&self) -> &dyn SessionApi { &self.session }
    fn conversation(&self) -> &dyn ConversationApi { &self.conversation }
    fn document(&self) -> &dyn DocumentApi { &self.document }
    fn mcp(&self) -> &dyn McpApi { &self.mcp }
    fn oauth(&self) -> &dyn OAuthApi { &self.oauth }
    fn model(&self) -> &dyn ModelApi { &self.model }
    fn asset(&self) -> &dyn AssetApi { &self.asset }
    fn voice(&self) -> &dyn VoiceApi { &self.voice }
    fn core(&self) -> &dyn CoreApi { &self.core }
    fn search(&self) -> &dyn SearchApi { &self.search }
    fn user(&self) -> &dyn UserApi { &self.user }
    fn tools(&self) -> &dyn simply_core::ToolService { &self.mcp }
}

// ToolService impl for RemoteMcpApi is in simply-daemon-api crate.
