//! RemoteDaemon — implements `Daemon` by composing generated remote API clients.
//!
//! Each API trait gets a `RemoteXxxApi` struct (generated by the macro) that
//! holds an `Arc<dyn RpcConnection>`. RemoteDaemon creates one per API trait
//! and delegates through the `Daemon` trait.

use std::sync::Arc;

use async_trait::async_trait;
use simply_rpc::RpcConnection;
use simply_rpc::ws_client::ConnectionState;
use tokio::sync::watch;

use crate::*;
use crate::client::DaemonRpcConnection;

/// A daemon client that talks to a remote daemon over REST + WebSocket.
pub struct RemoteDaemon {
    conn: Arc<DaemonRpcConnection>,
    session: RemoteSessionApi,
    conversation: RemoteConversationApi,
    asset: RemoteAssetApi,
    document: RemoteDocumentApi,
    mcp: RemoteMcpApi,
    oauth: RemoteOAuthApi,
    model: RemoteModelApi,
    voice: RemoteVoiceApi,
    core: RemoteCoreApi,
    search: RemoteSearchApi,
    user: RemoteUserApi,
    skills: RemoteSkillsApi,
}

impl RemoteDaemon {
    pub async fn connect_as(addr: &str, name: &str, daemon_secret: &str, user_id: Option<&str>) -> anyhow::Result<Arc<Self>> {
        let conn = Arc::new(DaemonRpcConnection::connect(addr, name, daemon_secret, user_id).await?);
        let rpc: Arc<dyn RpcConnection> = conn.clone();

        Ok(Arc::new(Self {
            session: RemoteSessionApi::new(rpc.clone()),
            conversation: RemoteConversationApi::new(rpc.clone()),
            asset: RemoteAssetApi::new(rpc.clone()),
            document: RemoteDocumentApi::new(rpc.clone()),
            mcp: RemoteMcpApi::new(rpc.clone()),
            oauth: RemoteOAuthApi::new(rpc.clone()),
            model: RemoteModelApi::new(rpc.clone()),
            voice: RemoteVoiceApi::new(rpc.clone()),
            core: RemoteCoreApi::new(rpc.clone()),
            search: RemoteSearchApi::new(rpc.clone()),
            user: RemoteUserApi::new(rpc.clone()),
            skills: RemoteSkillsApi::new(rpc),
            conn,
        }))
    }

    pub fn connection_state(&self) -> ConnectionState {
        self.conn.connection_state()
    }

    pub fn watch_connection_state(&self) -> watch::Receiver<ConnectionState> {
        self.conn.watch_state()
    }
}

#[async_trait]
impl Daemon for RemoteDaemon {
    fn session(&self) -> &dyn SessionApi { &self.session }
    fn conversation(&self) -> &dyn ConversationApi { &self.conversation }
    fn document(&self) -> &dyn DocumentApi { &self.document }
    fn mcp(&self) -> &dyn McpApi { &self.mcp }
    fn oauth(&self) -> &dyn OAuthApi { &self.oauth }
    fn model(&self) -> &dyn ModelApi { &self.model }
    fn asset(&self) -> &dyn AssetApi { &self.asset }
    fn voice(&self) -> &dyn VoiceApi { &self.voice }
    fn core(&self) -> &dyn CoreApi { &self.core }
    fn search(&self) -> &dyn SearchApi { &self.search }
    fn user(&self) -> &dyn UserApi { &self.user }
    fn skills(&self) -> &dyn SkillsApi { &self.skills }
    fn tools(&self) -> &dyn simply_core::ToolService { &self.mcp }

    async fn register_client_tools(
        &self,
        tools: Vec<llm::ToolDefinition>,
        handler: crate::ToolCallHandler,
    ) -> anyhow::Result<()> {
        // Set up reverse call handler that extracts __ctx and passes ToolCallContext
        let handler = handler.clone();
        self.conn.ws().set_reverse_handler(Arc::new(move |id, method, params, write_tx| {
            let handler = handler.clone();
            Box::pin(async move {
                if method != "tools.call" {
                    let resp = serde_json::json!({ "id": id, "error": { "message": format!("unknown reverse method: {method}") } });
                    let _ = write_tx.send(serde_json::to_string(&resp).unwrap_or_default()).await;
                    return;
                }

                let name = params.get("name").and_then(|v| v.as_str()).unwrap_or("").to_string();
                let arguments = params.get("arguments").cloned().unwrap_or(serde_json::Value::Null);
                let ctx = params.get("__ctx")
                    .and_then(|v| {
                        let tokens = v.get("tokens")
                            .and_then(|t| serde_json::from_value(t.clone()).ok())
                            .unwrap_or_default();
                        let user_id = v.get("user_id")
                            .and_then(|u| u.as_str())
                            .map(|s| s.to_string());
                        Some(crate::ToolCallContext { user_id, tokens })
                    })
                    .unwrap_or_default();

                let result = handler(name, arguments, ctx).await;
                let resp = match result {
                    Ok(value) => serde_json::json!({ "id": id, "result": value }),
                    Err(e) => serde_json::json!({ "id": id, "error": { "message": e.to_string() } }),
                };
                let _ = write_tx.send(serde_json::to_string(&resp).unwrap_or_default()).await;
            })
        })).await;

        // Send tools.register to daemon
        let result = self.conn.rpc_call(
            "tools.register",
            serde_json::json!({ "tools": tools }),
            &simply_rpc::RequestContext::anonymous(),
        ).await?;
        tracing::info!(result = %result, "client tools registered with daemon over WS");
        Ok(())
    }
}

// ToolService impl for RemoteMcpApi is in simply-daemon-api crate.
