//! RemoteDaemon — implements `Daemon` by composing generated remote API clients.
//!
//! Each API trait gets a `RemoteXxxApi` struct (generated by the macro) that
//! holds an `Arc<dyn RpcConnection>`. RemoteDaemon creates one per API trait
//! and delegates through the `Daemon` trait.

use std::sync::Arc;

use async_trait::async_trait;
use simply_rpc::RpcConnection;
use simply_rpc::ws_client::ConnectionState;
use tokio::sync::watch;

use crate::*;
use crate::client::DaemonRpcConnection;

/// A daemon client that talks to a remote daemon over REST + WebSocket.
pub struct RemoteDaemon {
    conn: Arc<DaemonRpcConnection>,
    session: RemoteSessionApi,
    conversation: RemoteConversationApi,
    asset: RemoteAssetApi,
    entity: RemoteEntityApi,
    mcp: RemoteMcpApi,
    oauth: RemoteOAuthApi,
    model: RemoteModelApi,
    voice: RemoteVoiceApi,
    core: RemoteCoreApi,
    search: RemoteSearchApi,
    vault: RemoteVaultApi,
    user: RemoteUserApi,
    skills: RemoteSkillsApi,
    /// Skills registered by this client, keyed by skill id.
    /// A single reverse-RPC handler dispatches by skill_id instead of each
    /// register_skill clobbering the previous handler.
    registered_skills: std::sync::Arc<tokio::sync::RwLock<std::collections::HashMap<String, std::sync::Arc<dyn crate::skill::Skill>>>>,
}

impl RemoteDaemon {
    pub async fn connect_as(addr: &str, name: &str, daemon_secret: &str, user_id: Option<&str>) -> anyhow::Result<Arc<Self>> {
        let conn = Arc::new(DaemonRpcConnection::connect(addr, name, daemon_secret, user_id).await?);
        let rpc: Arc<dyn RpcConnection> = conn.clone();

        let registered_skills: std::sync::Arc<tokio::sync::RwLock<std::collections::HashMap<String, std::sync::Arc<dyn crate::skill::Skill>>>> =
            std::sync::Arc::new(tokio::sync::RwLock::new(std::collections::HashMap::new()));

        // Install a single reverse-RPC handler that dispatches by __skill_id.
        let skills_map = std::sync::Arc::clone(&registered_skills);
        conn.ws().set_reverse_handler(std::sync::Arc::new(move |id, method, params, write_tx| {
            let skills_map = std::sync::Arc::clone(&skills_map);
            Box::pin(async move {
                if method != "tools.call" {
                    let resp = serde_json::json!({ "id": id, "error": { "message": format!("unknown reverse method: {method}") } });
                    let _ = write_tx.send(serde_json::to_string(&resp).unwrap_or_default()).await;
                    return;
                }

                let skill_id = params.get("__skill_id").and_then(|v| v.as_str()).unwrap_or("").to_string();
                let skill = { skills_map.read().await.get(&skill_id).cloned() };
                let Some(skill) = skill else {
                    let resp = serde_json::json!({ "id": id, "error": { "message": format!("no skill registered with id `{skill_id}`") } });
                    let _ = write_tx.send(serde_json::to_string(&resp).unwrap_or_default()).await;
                    return;
                };

                let tool_name = params.get("name").and_then(|v| v.as_str()).unwrap_or("").to_string();
                let arguments = params.get("arguments").cloned().unwrap_or(serde_json::Value::Null);
                // Deserialize the full RequestContext the daemon sent.
                let ctx: simply_rpc::RequestContext = params.get("__ctx")
                    .and_then(|v| serde_json::from_value(v.clone()).ok())
                    .unwrap_or_else(simply_rpc::RequestContext::anonymous);

                let result = skill.call_tool(&tool_name, arguments, &ctx).await;
                let resp = match result {
                    Ok(value) => serde_json::json!({ "id": id, "result": value }),
                    Err(e) => serde_json::json!({ "id": id, "error": { "message": e.to_string() } }),
                };
                let _ = write_tx.send(serde_json::to_string(&resp).unwrap_or_default()).await;
            })
        })).await;

        Ok(Arc::new(Self {
            session: RemoteSessionApi::new(rpc.clone()),
            conversation: RemoteConversationApi::new(rpc.clone()),
            asset: RemoteAssetApi::new(rpc.clone()),
            entity: RemoteEntityApi::new(rpc.clone()),
            mcp: RemoteMcpApi::new(rpc.clone()),
            oauth: RemoteOAuthApi::new(rpc.clone()),
            model: RemoteModelApi::new(rpc.clone()),
            voice: RemoteVoiceApi::new(rpc.clone()),
            core: RemoteCoreApi::new(rpc.clone()),
            search: RemoteSearchApi::new(rpc.clone()),
            vault: RemoteVaultApi::new(rpc.clone()),
            user: RemoteUserApi::new(rpc.clone()),
            skills: RemoteSkillsApi::new(rpc),
            registered_skills,
            conn,
        }))
    }

    pub fn connection_state(&self) -> ConnectionState {
        self.conn.connection_state()
    }

    pub fn watch_connection_state(&self) -> watch::Receiver<ConnectionState> {
        self.conn.watch_state()
    }
}

#[async_trait]
impl Daemon for RemoteDaemon {
    fn session(&self) -> &dyn SessionApi { &self.session }
    fn conversation(&self) -> &dyn ConversationApi { &self.conversation }
    fn entity(&self) -> &dyn EntityApi { &self.entity }
    fn mcp(&self) -> &dyn McpApi { &self.mcp }
    fn oauth(&self) -> &dyn OAuthApi { &self.oauth }
    fn model(&self) -> &dyn ModelApi { &self.model }
    fn asset(&self) -> &dyn AssetApi { &self.asset }
    fn voice(&self) -> &dyn VoiceApi { &self.voice }
    fn core(&self) -> &dyn CoreApi { &self.core }
    fn search(&self) -> &dyn SearchApi { &self.search }
    fn vault(&self) -> &dyn VaultApi { &self.vault }
    fn user(&self) -> &dyn UserApi { &self.user }
    fn skills(&self) -> &dyn SkillsApi { &self.skills }
    fn tools(&self) -> &dyn simply_core::ToolService { &self.mcp }

    /// Register a skill with the remote daemon.
    ///
    /// Stores the skill locally (keyed by name) and sends a `tools.register`
    /// WS message. The daemon dispatches tool calls back as reverse-RPC with
    /// a `__skill_id` field; a single shared handler (installed in `connect_as`)
    /// routes to the right skill.
    async fn register_skill(&self, skill: std::sync::Arc<dyn crate::skill::Skill>) -> anyhow::Result<()> {
        let name = skill.name().to_string();
        let tools = skill.tools();
        let oauth_reqs = skill.oauth_requirements();

        self.registered_skills.write().await.insert(name.clone(), skill);

        let result = self.conn.rpc_call(
            "tools.register",
            serde_json::json!({
                "id": name,
                "display_name": name,
                "tools": tools,
                "oauth_requirements": oauth_reqs,
            }),
            &simply_rpc::RequestContext::anonymous(),
        ).await?;
        tracing::info!(skill = %name, result = %result, "skill registered with daemon over WS");
        Ok(())
    }

    async fn register_client_tools(
        &self,
        tools: Vec<llm::ToolDefinition>,
        handler: crate::ToolCallHandler,
    ) -> anyhow::Result<()> {
        // Set up reverse call handler that extracts the full RequestContext.
        let handler = handler.clone();
        self.conn.ws().set_reverse_handler(Arc::new(move |id, method, params, write_tx| {
            let handler = handler.clone();
            Box::pin(async move {
                if method != "tools.call" {
                    let resp = serde_json::json!({ "id": id, "error": { "message": format!("unknown reverse method: {method}") } });
                    let _ = write_tx.send(serde_json::to_string(&resp).unwrap_or_default()).await;
                    return;
                }

                let name = params.get("name").and_then(|v| v.as_str()).unwrap_or("").to_string();
                let arguments = params.get("arguments").cloned().unwrap_or(serde_json::Value::Null);
                let ctx: simply_rpc::RequestContext = params.get("__ctx")
                    .and_then(|v| serde_json::from_value(v.clone()).ok())
                    .unwrap_or_else(simply_rpc::RequestContext::anonymous);

                let result = handler(name, arguments, ctx).await;
                let resp = match result {
                    Ok(value) => serde_json::json!({ "id": id, "result": value }),
                    Err(e) => serde_json::json!({ "id": id, "error": { "message": e.to_string() } }),
                };
                let _ = write_tx.send(serde_json::to_string(&resp).unwrap_or_default()).await;
            })
        })).await;

        // Send tools.register to daemon
        let result = self.conn.rpc_call(
            "tools.register",
            serde_json::json!({ "tools": tools }),
            &simply_rpc::RequestContext::anonymous(),
        ).await?;
        tracing::info!(result = %result, "client tools registered with daemon over WS");
        Ok(())
    }
}

// ToolService impl for RemoteMcpApi is in simply-daemon-api crate.
