use serde::{Deserialize, Serialize};

/// HTTP method (or WebSocket upgrade) for routing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum HttpMethod {
    Get,
    Post,
    Put,
    Delete,
    /// WebSocket upgrade — `#[rpc(stream = "/path")]`.
    Stream,
}

/// Metadata about a REST endpoint — generated by the macro from `#[rpc(get = "/path")]` etc.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RestMeta {
    pub http_method: HttpMethod,
    /// Path template, e.g. `"/session/{session_id}/message"`.
    pub path_template: &'static str,
    /// The RPC method name (e.g. `"session.send_message"`).
    pub method_name: &'static str,
    /// Doc comment for tool description.
    pub description: Option<&'static str>,
    /// Whether this method is excluded from tool generation.
    pub no_tool: bool,
}

/// Metadata about a single RPC method — generated by the macro.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct MethodMeta {
    pub name: &'static str,
    /// Hash of the method's parameter + return type tokens.
    pub signature_hash: u64,
    /// Exposed as HTTP GET: `GET /{prefix}/{param}` for single-param methods.
    pub rest_get: bool,
    /// Return value is base64-encoded (REST server decodes to raw bytes).
    pub base64_return: bool,
}

/// Metadata about an RPC service — compile-time constant generated by the macro.
#[derive(Debug, Clone)]
pub struct ServiceMeta {
    pub prefix: &'static str,
    pub methods: &'static [MethodMeta],
    pub rest_methods: &'static [RestMeta],
}

/// Wire-format service metadata for handshake exchange.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceMetaWire {
    pub prefix: String,
    pub methods: Vec<MethodMetaWire>,
}

/// Wire-format method metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MethodMetaWire {
    pub name: String,
    pub signature_hash: u64,
}

impl ServiceMeta {
    /// Convert to wire format for sending over the network.
    pub fn to_wire(&self) -> ServiceMetaWire {
        ServiceMetaWire {
            prefix: self.prefix.to_string(),
            methods: self
                .methods
                .iter()
                .map(|m| MethodMetaWire {
                    name: m.name.to_string(),
                    signature_hash: m.signature_hash,
                })
                .collect(),
        }
    }
}

/// Result of a compatibility check.
#[derive(Debug)]
pub struct CompatResult {
    pub compatible: bool,
    pub missing: Vec<String>,
    pub mismatched: Vec<String>,
}

impl std::fmt::Display for CompatResult {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if self.compatible {
            write!(f, "compatible")
        } else {
            write!(f, "incompatible:")?;
            for m in &self.missing {
                write!(f, " missing={m}")?;
            }
            for m in &self.mismatched {
                write!(f, " changed={m}")?;
            }
            Ok(())
        }
    }
}

/// Check if a client's expected methods are satisfied by the server.
///
/// Compatible if every client method exists on the server with the same signature hash.
/// The server may have extra methods — that's fine.
pub fn check_compat(client: &[ServiceMetaWire], server: &[&ServiceMeta]) -> CompatResult {
    let mut missing = Vec::new();
    let mut mismatched = Vec::new();

    for client_svc in client {
        let server_svc = server.iter().find(|s| s.prefix == client_svc.prefix);

        for client_method in &client_svc.methods {
            match server_svc {
                None => {
                    missing.push(client_method.name.clone());
                }
                Some(server_svc) => {
                    match server_svc
                        .methods
                        .iter()
                        .find(|m| m.name == client_method.name)
                    {
                        None => missing.push(client_method.name.clone()),
                        Some(server_method) => {
                            if server_method.signature_hash != client_method.signature_hash {
                                mismatched.push(client_method.name.clone());
                            }
                        }
                    }
                }
            }
        }
    }

    CompatResult {
        compatible: missing.is_empty() && mismatched.is_empty(),
        missing,
        mismatched,
    }
}
