use std::collections::HashMap;
use std::sync::Arc;

use async_trait::async_trait;
use serde_json::Value;

use crate::DispatchResult;
use crate::RpcResult;

/// A dispatchable RPC service. Generated by `#[rpc_service("prefix")]`.
///
/// Each service defines its own `Stream` type for methods annotated with
/// `#[rpc(stream)]`. Services with no stream methods use `Stream = ()`.
#[async_trait]
pub trait RpcService: Send + Sync {
    /// The stream type produced by `#[rpc(stream)]` methods.
    type Stream: Send + 'static;

    /// The method prefix (e.g. "session", "mcp").
    fn prefix(&self) -> &str;

    /// Metadata for compatibility checking. Generated by the macro.
    fn meta(&self) -> &'static crate::ServiceMeta;

    /// Dispatch a method call. Returns `None` if the method doesn't belong to this service.
    async fn dispatch(
        &self,
        method: &str,
        params: Value,
    ) -> Option<DispatchResult<Self::Stream>>;
}

/// Pre-built dispatcher with prefix → service lookup.
/// For services with `Stream = ()` only.
///
/// For stream-producing services, dispatch them individually before falling through to this.
#[derive(Clone)]
pub struct Dispatcher {
    services: HashMap<String, Arc<dyn RpcService<Stream = ()>>>,
}

impl Dispatcher {
    pub fn new() -> Self {
        Self {
            services: HashMap::new(),
        }
    }

    /// Register a service. Panics on duplicate prefix.
    pub fn register(mut self, svc: Arc<dyn RpcService<Stream = ()>>) -> Self {
        let prefix = svc.prefix().to_string();
        if self.services.contains_key(&prefix) {
            panic!("duplicate RPC service prefix: {prefix}");
        }
        self.services.insert(prefix, svc);
        self
    }

    /// Dispatch a method call. Extracts prefix from the method name and routes directly.
    pub async fn dispatch(&self, method: &str, params: Value) -> RpcResult {
        let prefix = method.split('.').next().unwrap_or("");
        match self.services.get(prefix) {
            Some(svc) => match svc.dispatch(method, params).await {
                Some(dr) => dr.result,
                None => Err(anyhow::anyhow!("unknown method: {method}")),
            },
            None => Err(anyhow::anyhow!("unknown method: {method}")),
        }
    }

    /// Collect metadata from all registered services (for compatibility handshake).
    pub fn service_metas(&self) -> Vec<&'static crate::ServiceMeta> {
        self.services.values().map(|svc| svc.meta()).collect()
    }
}

impl Default for Dispatcher {
    fn default() -> Self {
        Self::new()
    }
}

/// Trait for services that can dispatch REST requests by method name.
///
/// Auto-implemented by the macro. The service handles deserialization and
/// trait method calls. Path matching is handled by `RestDispatcher` using matchit.
#[async_trait]
pub trait RestService: Send + Sync {
    /// Dispatch a REST request by method name (e.g. "items.get_item").
    /// `params` is a JSON object with all parameters (path params merged with body).
    async fn rest_dispatch_by_name(
        &self,
        method_name: &str,
        params: Value,
    ) -> Option<RpcResult>;

    /// Get metadata for route registration and compatibility checking.
    fn meta(&self) -> &'static crate::ServiceMeta;
}

/// Route entry stored in the matchit router.
struct RouteEntry {
    /// The RPC method name (e.g. "items.get_item")
    method_name: &'static str,
    /// The service that handles this method
    service: Arc<dyn RestService>,
}

/// Dispatcher that routes REST requests using matchit for path matching.
///
/// Build with `register()` to add services. Each service's `RouteMeta` entries
/// are inserted into per-HTTP-method routers. At dispatch time, matchit resolves
/// the path, extracts params, merges with body, and calls the service.
pub struct RestDispatcher {
    routers: HashMap<crate::HttpMethod, matchit::Router<RouteEntry>>,
    services: Vec<Arc<dyn RestService>>,
}

impl RestDispatcher {
    pub fn new() -> Self {
        Self {
            routers: HashMap::new(),
            services: Vec::new(),
        }
    }

    /// Register a REST service. Routes are extracted from its metadata.
    pub fn register(mut self, svc: Arc<dyn RestService>) -> Self {
        let meta = svc.meta();
        for rm in meta.routes {
            let http_method = match rm.kind {
                crate::RouteKind::Rest(m) => m,
                crate::RouteKind::Stream => continue, // Stream routes handled by WS layer
            };
            let router = self.routers.entry(http_method).or_insert_with(matchit::Router::new);
            let entry = RouteEntry {
                method_name: rm.method_name,
                service: svc.clone(),
            };
            if let Err(e) = router.insert(rm.path_template, entry) {
                panic!("failed to register route {} {}: {}", rm.path_template, rm.method_name, e);
            }
        }
        self.services.push(svc);
        self
    }

    /// Dispatch an HTTP request. Uses matchit to resolve path, extract params,
    /// merge with body, and call the appropriate service.
    pub async fn dispatch(
        &self,
        http_method: crate::HttpMethod,
        path: &str,
        body: Value,
    ) -> Option<RpcResult> {
        let router = self.routers.get(&http_method)?;
        let matched = router.at(path).ok()?;
        let entry = matched.value;

        // Merge path params into body (or create object if body is null)
        let params = if matched.params.is_empty() {
            body
        } else {
            let mut obj = match body {
                Value::Object(map) => map,
                Value::Null => serde_json::Map::new(),
                other => {
                    // Single body value — wrap it (shouldn't normally happen with path params)
                    let mut map = serde_json::Map::new();
                    map.insert("_body".to_string(), other);
                    map
                }
            };
            for (key, value) in matched.params.iter() {
                obj.insert(key.to_string(), Value::String(value.to_string()));
            }
            Value::Object(obj)
        };

        entry.service.rest_dispatch_by_name(entry.method_name, params).await
    }

    /// Collect route metadata from all registered services.
    pub fn route_metas(&self) -> Vec<&'static crate::RouteMeta> {
        self.services
            .iter()
            .flat_map(|svc| svc.meta().routes.iter())
            .collect()
    }
}

impl Default for RestDispatcher {
    fn default() -> Self {
        Self::new()
    }
}
