use std::collections::HashMap;
use std::sync::Arc;

use async_trait::async_trait;
use serde_json::Value;

use crate::DispatchResult;
use crate::RpcResult;

/// A dispatchable RPC service. Generated by `#[rpc_service("prefix")]`.
///
/// Each service defines its own `Stream` type for methods annotated with
/// `#[rpc(stream)]`. Services with no stream methods use `Stream = ()`.
#[async_trait]
pub trait RpcService: Send + Sync {
    /// The stream type produced by `#[rpc(stream)]` methods.
    type Stream: Send + 'static;

    /// The method prefix (e.g. "session", "mcp").
    fn prefix(&self) -> &str;

    /// Metadata for compatibility checking. Generated by the macro.
    fn meta(&self) -> &'static crate::ServiceMeta;

    /// Dispatch a method call. Returns `None` if the method doesn't belong to this service.
    async fn dispatch(
        &self,
        method: &str,
        params: Value,
    ) -> Option<DispatchResult<Self::Stream>>;
}

/// Pre-built dispatcher with prefix → service lookup.
/// For services with `Stream = ()` only.
///
/// For stream-producing services, dispatch them individually before falling through to this.
#[derive(Clone)]
pub struct Dispatcher {
    services: HashMap<String, Arc<dyn RpcService<Stream = ()>>>,
}

impl Dispatcher {
    pub fn new() -> Self {
        Self {
            services: HashMap::new(),
        }
    }

    /// Register a service. Panics on duplicate prefix.
    pub fn register(mut self, svc: Arc<dyn RpcService<Stream = ()>>) -> Self {
        let prefix = svc.prefix().to_string();
        if self.services.contains_key(&prefix) {
            panic!("duplicate RPC service prefix: {prefix}");
        }
        self.services.insert(prefix, svc);
        self
    }

    /// Dispatch a method call. Extracts prefix from the method name and routes directly.
    pub async fn dispatch(&self, method: &str, params: Value) -> RpcResult {
        let prefix = method.split('.').next().unwrap_or("");
        match self.services.get(prefix) {
            Some(svc) => match svc.dispatch(method, params).await {
                Some(dr) => dr.result,
                None => Err(anyhow::anyhow!("unknown method: {method}")),
            },
            None => Err(anyhow::anyhow!("unknown method: {method}")),
        }
    }

    /// Collect metadata from all registered services (for compatibility handshake).
    pub fn service_metas(&self) -> Vec<&'static crate::ServiceMeta> {
        self.services.values().map(|svc| svc.meta()).collect()
    }
}

impl Default for Dispatcher {
    fn default() -> Self {
        Self::new()
    }
}
