//! RemoteDaemon — implements `Daemon` by composing generated remote API clients.
//!
//! Each API trait gets a `RemoteXxxApi` struct (generated by the macro) that
//! holds an `Arc<dyn RpcConnection>`. RemoteDaemon creates one per API trait
//! and delegates through the `Daemon` trait.

use std::sync::Arc;

use async_trait::async_trait;
use simply_rpc::RpcConnection;
use simply_rpc::ws_client::ConnectionState;
use tokio::sync::watch;

use crate::api::*;
use crate::net::client::DaemonRpcConnection;

/// A daemon client that talks to a remote daemon over REST + WebSocket.
pub struct RemoteDaemon {
    conn: Arc<DaemonRpcConnection>,
    session: RemoteSessionApi,
    conversation: RemoteConversationApi,
    asset: RemoteAssetApi,
    mcp: RemoteMcpApi,
    oauth: RemoteOAuthApi,
    model: RemoteModelApi,
    voice: RemoteVoiceApi,
    core: RemoteCoreApi,
}

impl RemoteDaemon {
    pub async fn connect(addr: &str) -> anyhow::Result<Arc<Self>> {
        Self::connect_as(addr, "unknown").await
    }

    pub async fn connect_as(addr: &str, name: &str) -> anyhow::Result<Arc<Self>> {
        let conn = Arc::new(DaemonRpcConnection::connect(addr, name).await?);
        let rpc: Arc<dyn RpcConnection> = conn.clone();

        Ok(Arc::new(Self {
            session: RemoteSessionApi::new(rpc.clone()),
            conversation: RemoteConversationApi::new(rpc.clone()),
            asset: RemoteAssetApi::new(rpc.clone()),
            mcp: RemoteMcpApi::new(rpc.clone()),
            oauth: RemoteOAuthApi::new(rpc.clone()),
            model: RemoteModelApi::new(rpc.clone()),
            voice: RemoteVoiceApi::new(rpc.clone()),
            core: RemoteCoreApi::new(rpc),
            conn,
        }))
    }

    pub fn connection_state(&self) -> ConnectionState {
        self.conn.connection_state()
    }

    pub fn watch_connection_state(&self) -> watch::Receiver<ConnectionState> {
        self.conn.watch_state()
    }
}

impl Daemon for RemoteDaemon {
    fn session(&self) -> &dyn SessionApi { &self.session }
    fn conversation(&self) -> &dyn ConversationApi { &self.conversation }
    fn mcp(&self) -> &dyn McpApi { &self.mcp }
    fn oauth(&self) -> &dyn OAuthApi { &self.oauth }
    fn model(&self) -> &dyn ModelApi { &self.model }
    fn asset(&self) -> &dyn AssetApi { &self.asset }
    fn voice(&self) -> &dyn VoiceApi { &self.voice }
    fn core(&self) -> &dyn CoreApi { &self.core }
    fn tools(&self) -> &dyn simply_core::ToolService { &self.mcp }
}

/// Remote tool service — delegates to the MCP remote client.
#[async_trait]
impl simply_core::ToolService for RemoteMcpApi {
    async fn get_definitions(&self) -> Vec<llm::ToolDefinition> {
        McpApi::list_all_tools(self).await
            .unwrap_or_default()
            .into_iter()
            .map(|t| llm::ToolDefinition {
                name: t.name.to_string(),
                description: t.description.map(|d| d.to_string()),
                input_schema: serde_json::from_value(
                    serde_json::to_value(&*t.input_schema).unwrap_or_default()
                ).unwrap_or_default(),
            })
            .collect()
    }

    async fn call_tool(
        &self,
        name: &str,
        arguments: serde_json::Value,
    ) -> anyhow::Result<Vec<llm::ToolResultContent>> {
        let result = McpApi::call_tool_direct(
            self,
            CallToolRequestParam::new(name.to_string())
                .with_arguments(arguments.as_object().cloned().unwrap_or_default()),
        ).await?;
        Ok(result.content.into_iter().filter_map(|c| {
            match c.raw {
                rmcp::model::RawContent::Text(t) => Some(llm::ToolResultContent::text(t.text)),
                _ => None,
            }
        }).collect())
    }
}
