# Lumina configuration
#
# Copy this file to ~/.local/share/noema/config/lumina.toml
# and fill in your Discord bot token.

[discord]
bot_token = ""
owner_id = 358478627270295563
guild_ids = [1341429255367688253, 1353728601010470993]
