//! Lumina MCP server — exposes Discord actions as tools via MCP.
//!
//! Lumina registers this server with the daemon on connect, making
//! Discord tools available to any daemon agent (Noema, spawned agents, etc).
//!
//! Tool definitions and dispatch are generated by `#[mcp_tools]` / `#[mcp_tool]`
//! from the annotated handler methods in `tools.rs`.

pub mod param;
mod tools;

pub use param::McpParam;

use rmcp::{
    handler::server::ServerHandler,
    model::*,
    service::{RequestContext, RoleServer},
    ErrorData as McpError,
};
use serenity::all::Cache;
use serenity::http::Http;
use std::sync::{Arc, OnceLock};

// ---------------------------------------------------------------------------
// Server
// ---------------------------------------------------------------------------

/// MCP server exposing Discord tools through Lumina.
#[derive(Clone)]
pub struct LuminaMcpServer {
    inner: Arc<LuminaMcpServerInner>,
}

struct LuminaMcpServerInner {
    http: Arc<Http>,
    cache: OnceLock<Arc<Cache>>,
}

impl LuminaMcpServer {
    pub fn new(http: Arc<Http>) -> Self {
        Self {
            inner: Arc::new(LuminaMcpServerInner {
                http,
                cache: OnceLock::new(),
            }),
        }
    }

    /// Inject the serenity cache once the gateway is connected.
    /// Called from the `ready` event handler.
    pub fn set_cache(&self, cache: Arc<Cache>) {
        let _ = self.inner.cache.set(cache);
    }

    pub(crate) fn http(&self) -> &Arc<Http> {
        &self.inner.http
    }

    pub(crate) fn cache(&self) -> Option<&Arc<Cache>> {
        self.inner.cache.get()
    }
}

// ---------------------------------------------------------------------------
// ServerHandler
// ---------------------------------------------------------------------------

impl ServerHandler for LuminaMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            protocol_version: ProtocolVersion::V_2024_11_05,
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            server_info: Implementation {
                name: "lumina-discord".into(),
                version: env!("CARGO_PKG_VERSION").into(),
            },
            instructions: Some(
                "Lumina Discord MCP server. Provides tools for interacting with Discord \
                 channels, messages, guilds, and users."
                    .into(),
            ),
        }
    }

    fn list_tools(
        &self,
        _request: Option<PaginatedRequestParam>,
        _context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<ListToolsResult, McpError>> + Send + '_ {
        std::future::ready(Ok(ListToolsResult {
            tools: Self::mcp_definitions(),
            next_cursor: None,
        }))
    }

    fn call_tool(
        &self,
        request: CallToolRequestParam,
        _context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<CallToolResult, McpError>> + Send + '_ {
        async move {
            let name = request.name.as_ref();
            let args = request.arguments.unwrap_or_default();

            tracing::info!(tool = name, "lumina mcp: tool call");

            let result = self.mcp_dispatch(name, args).await;

            Ok(match result {
                Ok(value) => CallToolResult::success(vec![Content::text(
                    serde_json::to_string_pretty(&value).unwrap_or_default(),
                )]),
                Err(e) => {
                    tracing::warn!(tool = name, error = %e, "tool call failed");
                    CallToolResult::error(vec![Content::text(format!("{e}"))])
                }
            })
        }
    }
}
