//! Lumina MCP server — exposes Discord actions as tools via MCP.
//!
//! Lumina registers this server with the daemon on connect, making
//! Discord tools available to any daemon agent (Noema, spawned agents, etc).
//!
//! Tool definitions and dispatch are generated by rmcp's `#[tool]` /
//! `#[tool_router]` / `#[tool_handler]` macros from the annotated
//! handler methods in `tools.rs`.

pub mod param;
mod tools;

use rmcp::handler::server::router::tool::ToolRouter;
use serenity::all::Cache;
use serenity::http::Http;
use std::sync::{Arc, OnceLock};

// ---------------------------------------------------------------------------
// Server
// ---------------------------------------------------------------------------

/// MCP server exposing Discord tools through Lumina.
#[derive(Clone)]
pub struct LuminaMcpServer {
    inner: Arc<LuminaMcpServerInner>,
    tool_router: ToolRouter<Self>,
}

struct LuminaMcpServerInner {
    http: Arc<Http>,
    cache: OnceLock<Arc<Cache>>,
}

impl LuminaMcpServer {
    pub fn new(http: Arc<Http>) -> Self {
        let inner = Arc::new(LuminaMcpServerInner {
            http,
            cache: OnceLock::new(),
        });
        Self {
            inner,
            tool_router: Self::tool_router(),
        }
    }

    /// Inject the serenity cache once the gateway is connected.
    /// Called from the `ready` event handler.
    pub fn set_cache(&self, cache: Arc<Cache>) {
        let _ = self.inner.cache.set(cache);
    }

    pub(crate) fn http(&self) -> &Arc<Http> {
        &self.inner.http
    }

    pub(crate) fn cache(&self) -> Option<&Arc<Cache>> {
        self.inner.cache.get()
    }
}

// ---------------------------------------------------------------------------
// ServerHandler — call_tool + list_tools generated by #[tool_handler]
// ---------------------------------------------------------------------------

#[rmcp::tool_handler]
impl rmcp::handler::server::ServerHandler for LuminaMcpServer {}
