//! Lumina MCP server — exposes Discord actions as tools via MCP.
//!
//! Lumina registers this server with the daemon on connect, making
//! Discord tools available to any daemon agent (Noema, spawned agents, etc).
//!
//! Tool definitions and dispatch are generated by rmcp's `#[tool]` /
//! `#[tool_router]` / `#[tool_handler]` macros from the annotated
//! handler methods in `tools.rs`.

pub mod param;
mod tools;

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::ServerHandler;
use rmcp::model::*;
use rmcp::service::{RequestContext, RoleServer};
use serenity::all::Cache;
use serenity::http::Http;
use std::sync::{Arc, OnceLock};

// ---------------------------------------------------------------------------
// Server
// ---------------------------------------------------------------------------

/// MCP server exposing Discord tools through Lumina.
#[derive(Clone)]
pub struct LuminaMcpServer {
    inner: Arc<LuminaMcpServerInner>,
    tool_router: ToolRouter<Self>,
}

struct LuminaMcpServerInner {
    http: Arc<Http>,
    cache: OnceLock<Arc<Cache>>,
    /// Instructions with guild/channel map, refreshed when channels change.
    instructions: std::sync::RwLock<String>,
}

impl LuminaMcpServer {
    const BASE_INSTRUCTIONS: &str =
        "Lumina Discord MCP server. Provides tools for interacting with Discord \
         channels, messages, guilds, and users.";

    pub fn new(http: Arc<Http>) -> Self {
        let inner = Arc::new(LuminaMcpServerInner {
            http,
            cache: OnceLock::new(),
            instructions: std::sync::RwLock::new(Self::BASE_INSTRUCTIONS.to_string()),
        });
        Self {
            inner,
            tool_router: Self::tool_router(),
        }
    }

    /// Inject the serenity cache once the gateway is connected.
    /// Called from the `ready` event handler.
    pub fn set_cache(&self, cache: Arc<Cache>) {
        let _ = self.inner.cache.set(cache);
        self.refresh_instructions();
    }

    /// Rebuild the instructions string from the current gateway cache.
    /// Call this when guild/channel state may have changed.
    pub fn refresh_instructions(&self) {
        let Some(cache) = self.inner.cache.get() else { return };

        let mut text = String::from(Self::BASE_INSTRUCTIONS);
        text.push_str("\n\n## Available Discord Servers & Channels\n");

        for guild_id in cache.guilds() {
            let Some(guild) = cache.guild(guild_id) else { continue };
            text.push_str(&format!("\n### {} (guild_id: {})\n", guild.name, guild_id.get()));

            // Group channels by category
            let mut categories: std::collections::BTreeMap<Option<serenity::model::id::ChannelId>, Vec<&serenity::model::channel::GuildChannel>> =
                std::collections::BTreeMap::new();

            for ch in guild.channels.values() {
                if ch.kind == serenity::model::channel::ChannelType::Category {
                    continue;
                }
                categories.entry(ch.parent_id).or_default().push(ch);
            }

            for (parent_id, channels) in &categories {
                if let Some(pid) = parent_id {
                    if let Some(cat) = guild.channels.get(pid) {
                        text.push_str(&format!("\n**{}**\n", cat.name));
                    }
                }
                let mut sorted: Vec<_> = channels.iter().collect();
                sorted.sort_by_key(|ch| ch.position);
                for ch in sorted {
                    let kind = match ch.kind {
                        serenity::model::channel::ChannelType::Voice => "voice",
                        serenity::model::channel::ChannelType::Forum => "forum",
                        serenity::model::channel::ChannelType::Stage => "stage",
                        _ => "text",
                    };
                    text.push_str(&format!("- #{} (id: {}, {})\n", ch.name, ch.id.get(), kind));
                }
            }
        }

        if let Ok(mut instructions) = self.inner.instructions.write() {
            *instructions = text;
        }
    }

    fn instructions(&self) -> String {
        self.inner.instructions.read()
            .map(|s| s.clone())
            .unwrap_or_else(|_| Self::BASE_INSTRUCTIONS.to_string())
    }

    pub(crate) fn http(&self) -> &Arc<Http> {
        &self.inner.http
    }

    pub(crate) fn cache(&self) -> Option<&Arc<Cache>> {
        self.inner.cache.get()
    }
}

// ---------------------------------------------------------------------------
// ServerHandler — call_tool + list_tools generated by #[tool_handler]
// ---------------------------------------------------------------------------

#[rmcp::tool_handler]
impl ServerHandler for LuminaMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            protocol_version: ProtocolVersion::V_2024_11_05,
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            server_info: Implementation {
                name: "lumina-discord".into(),
                version: env!("CARGO_PKG_VERSION").into(),
            },
            instructions: Some(self.instructions().into()),
        }
    }
}
