//! Discord MCP tool handlers — annotated with `#[mcp_tool]`.
//!
//! Tool definitions, dispatch, and argument deserialization are all
//! generated by the `#[mcp_tools]` proc macro from the function signatures.

use super::LuminaMcpServer;
use super::param::*;
use anyhow::{Context as _, Result};
use serde_json::{json, Value};
use serenity::builder::{CreateEmbed, CreateMessage, GetMessages};
use serenity::model::id::ChannelId as SerenityChannelId;
use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const DISCORD_EPOCH_MS: u64 = 1_420_070_400_000;

fn snowflake_hours_ago(hours: u64) -> serenity::model::id::MessageId {
    let now_ms = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_millis() as u64;
    let target_ms = now_ms.saturating_sub(hours * 3_600_000);
    serenity::model::id::MessageId::new((target_ms.saturating_sub(DISCORD_EPOCH_MS)) << 22)
}

async fn fetch_messages_since(
    http: &serenity::http::Http,
    channel_id: SerenityChannelId,
    after: serenity::model::id::MessageId,
    max: usize,
) -> Result<Vec<serenity::model::channel::Message>> {
    let mut all = Vec::new();
    let mut cursor = after;
    loop {
        let batch = channel_id
            .messages(http, GetMessages::new().after(cursor).limit(100))
            .await?;
        if batch.is_empty() { break; }
        cursor = batch.iter().map(|m| m.id).max().unwrap_or(cursor);
        all.extend(batch);
        if all.len() >= max { all.truncate(max); break; }
    }
    Ok(all)
}

fn build_embed(title: Option<&str>, description: Option<&str>, color: Option<&str>) -> Option<CreateEmbed> {
    if title.is_none() && description.is_none() { return None; }
    let mut embed = CreateEmbed::new();
    if let Some(t) = title { embed = embed.title(t); }
    if let Some(d) = description { embed = embed.description(d); }
    if let Some(hex) = color {
        if let Ok(c) = u32::from_str_radix(hex.trim_start_matches('#'), 16) {
            embed = embed.color(c);
        }
    }
    Some(embed)
}

fn message_to_json(msg: &serenity::model::channel::Message) -> Value {
    json!({
        "id": msg.id.get(),
        "channel_id": msg.channel_id.get(),
        "author": { "id": msg.author.id.get(), "name": msg.author.name },
        "content": msg.content,
        "timestamp": msg.timestamp.to_string(),
        "reactions": msg.reactions.iter().map(|r| json!({
            "emoji": r.reaction_type.to_string(), "count": r.count,
        })).collect::<Vec<_>>(),
        "attachments": msg.attachments.len(),
        "embeds": msg.embeds.len(),
    })
}

const NUMBER_EMOJIS: &[&str] = &["1️⃣", "2️⃣", "3️⃣", "4️⃣", "5️⃣", "6️⃣", "7️⃣", "8️⃣", "9️⃣", "🔟"];

// ---------------------------------------------------------------------------
// Tool handlers — schemas and dispatch generated by #[mcp_tools]
// ---------------------------------------------------------------------------

#[lumina_macros::mcp_tools]
impl LuminaMcpServer {

    // -- Messaging --

    #[mcp_tool(description = "Send a message to a Discord channel")]
    async fn send_message(
        &self,
        channel_id: ChannelId,
        #[describe("Message content")] content: String,
        #[describe("Optional embed title")] embed_title: Option<String>,
        #[describe("Optional embed description")] embed_description: Option<String>,
        #[describe("Hex color code (e.g. #FF0000)")] embed_color: Option<String>,
    ) -> Result<Value> {
        let ch = channel_id.serenity();
        let mut msg = CreateMessage::new().content(&content);
        if let Some(embed) = build_embed(
            embed_title.as_deref(), embed_description.as_deref(), embed_color.as_deref(),
        ) {
            msg = msg.embed(embed);
        }
        let sent = ch.send_message(self.http(), msg).await?;
        Ok(json!({
            "status": "success",
            "message_id": sent.id.get(),
            "channel_id": sent.channel_id.get(),
        }))
    }

    #[mcp_tool(description = "Reply to a specific message in a Discord channel")]
    async fn reply_to_message(
        &self,
        channel_id: ChannelId,
        message_id: MessageId,
        #[describe("Reply content")] content: String,
        #[describe("Mention the original author (default true)")] mention_author: Option<bool>,
        #[describe("Optional embed title")] embed_title: Option<String>,
        #[describe("Optional embed description")] embed_description: Option<String>,
        #[describe("Hex color code")] embed_color: Option<String>,
    ) -> Result<Value> {
        let ch = channel_id.serenity();
        let ref_msg = ch.message(self.http(), message_id.serenity()).await?;
        let mut msg = CreateMessage::new().content(&content).reference_message(&ref_msg);
        if let Some(embed) = build_embed(
            embed_title.as_deref(), embed_description.as_deref(), embed_color.as_deref(),
        ) {
            msg = msg.embed(embed);
        }
        if mention_author == Some(false) {
            msg = msg.allowed_mentions(
                serenity::builder::CreateAllowedMentions::new().replied_user(false),
            );
        }
        let sent = ch.send_message(self.http(), msg).await?;
        Ok(json!({ "status": "success", "message_id": sent.id.get() }))
    }

    #[mcp_tool(description = "Send a rich embed message to a Discord channel")]
    async fn create_embed(
        &self,
        channel_id: ChannelId,
        #[describe("Embed title")] title: String,
        #[describe("Embed description")] description: String,
        #[describe("Field names")] fields_names: Option<Vec<String>>,
        #[describe("Field values")] fields_values: Option<Vec<String>>,
    ) -> Result<Value> {
        let ch = channel_id.serenity();
        let mut embed = CreateEmbed::new().title(&title).description(&description).color(0x1ABC9C);
        if let (Some(names), Some(values)) = (&fields_names, &fields_values) {
            for (name, value) in names.iter().zip(values.iter()) {
                let v = if value.len() > 1024 { format!("{}...", &value[..1021]) } else { value.clone() };
                embed = embed.field(name, v, false);
            }
        }
        let sent = ch.send_message(self.http(), CreateMessage::new().embed(embed)).await?;
        Ok(json!({ "status": "success", "message_id": sent.id.get() }))
    }

    #[mcp_tool(description = "Create a reaction-based poll in a Discord channel")]
    async fn create_poll(
        &self,
        channel_id: ChannelId,
        #[describe("Poll question")] question: String,
        #[describe("Poll options (max 10)")] options: Vec<String>,
        #[describe("Custom emojis for options")] emojis: Option<Vec<String>>,
    ) -> Result<Value> {
        if options.len() > 10 { anyhow::bail!("maximum 10 poll options"); }
        let ch = channel_id.serenity();
        let emoji_list = emojis.as_deref().unwrap_or(&[]);
        let text: Vec<String> = options.iter().enumerate().map(|(i, opt)| {
            let e = emoji_list.get(i).map(|s| s.as_str())
                .unwrap_or(NUMBER_EMOJIS.get(i).copied().unwrap_or("▪️"));
            format!("{e} - {opt}")
        }).collect();
        let embed = CreateEmbed::new()
            .title(format!("📋 Poll: {question}"))
            .description(text.join("\n"))
            .color(0x3498DB);
        let sent = ch.send_message(self.http(), CreateMessage::new().embed(embed)).await?;
        for (i, _) in options.iter().enumerate() {
            let e = emoji_list.get(i).map(|s| s.as_str())
                .unwrap_or(NUMBER_EMOJIS.get(i).copied().unwrap_or("▪️"));
            sent.react(self.http(), serenity::model::channel::ReactionType::Unicode(e.to_string())).await?;
        }
        Ok(json!({ "status": "success", "message_id": sent.id.get(), "options_count": options.len() }))
    }

    // -- Read --

    #[mcp_tool(description = "Get message history from a Discord channel")]
    async fn get_channel_history(
        &self,
        channel_id: ChannelId,
        #[describe("Max messages to fetch (default 100, max 1000)")] limit: Option<u64>,
    ) -> Result<Value> {
        let ch = channel_id.serenity();
        let limit = limit.unwrap_or(100).min(1000);
        let mut all = Vec::new();
        let mut before: Option<serenity::model::id::MessageId> = None;
        let mut remaining = limit;
        while remaining > 0 {
            let batch_size = remaining.min(100) as u8;
            let mut req = GetMessages::new().limit(batch_size);
            if let Some(id) = before { req = req.before(id); }
            let batch = ch.messages(self.http(), req).await?;
            if batch.is_empty() { break; }
            before = batch.last().map(|m| m.id);
            remaining = remaining.saturating_sub(batch.len() as u64);
            all.extend(batch);
        }
        let messages: Vec<Value> = all.iter().map(message_to_json).collect();
        Ok(json!({ "status": "success", "messages": messages, "count": messages.len() }))
    }

    #[mcp_tool(description = "Search for messages in a channel containing specific text")]
    async fn search_messages(
        &self,
        channel_id: ChannelId,
        #[describe("Text to search for (case-insensitive)")] query: String,
        #[describe("Max messages to scan (default 100)")] limit: Option<u64>,
    ) -> Result<Value> {
        let ch = channel_id.serenity();
        let limit = limit.unwrap_or(100).min(1000);
        let query_lower = query.to_lowercase();
        let mut before: Option<serenity::model::id::MessageId> = None;
        let mut remaining = limit;
        let mut matches = Vec::new();
        while remaining > 0 {
            let batch_size = remaining.min(100) as u8;
            let mut req = GetMessages::new().limit(batch_size);
            if let Some(id) = before { req = req.before(id); }
            let batch = ch.messages(self.http(), req).await?;
            if batch.is_empty() { break; }
            before = batch.last().map(|m| m.id);
            remaining = remaining.saturating_sub(batch.len() as u64);
            for msg in &batch {
                if msg.content.to_lowercase().contains(&query_lower) {
                    matches.push(message_to_json(msg));
                }
            }
        }
        Ok(json!({ "status": "success", "messages": matches, "count": matches.len() }))
    }

    #[mcp_tool(description = "List all channels in a guild")]
    async fn list_channels(&self, guild_id: GuildId) -> Result<Value> {
        let channels = guild_id.serenity().channels(self.http()).await?;
        let list: Vec<Value> = channels.values().map(|ch| json!({
            "name": ch.name, "id": ch.id.get(),
            "kind": format!("{:?}", ch.kind),
            "parent_id": ch.parent_id.map(|p| p.get()),
        })).collect();
        Ok(json!({ "status": "success", "channels": list, "count": list.len() }))
    }

    #[mcp_tool(description = "List all guilds the bot is in")]
    async fn list_guilds(&self) -> Result<Value> {
        let cache = self.cache().context("gateway cache not available yet")?;
        let guilds: Vec<Value> = cache.guilds().iter().filter_map(|id| {
            cache.guild(*id).map(|g| json!({ "name": g.name.clone(), "id": id.get() }))
        }).collect();
        Ok(json!({ "status": "success", "guilds": guilds, "count": guilds.len() }))
    }

    #[mcp_tool(description = "Get custom emojis in a guild")]
    async fn get_emoji_list(&self, guild_id: GuildId) -> Result<Value> {
        let emojis = guild_id.serenity().emojis(self.http()).await?;
        let list: Vec<Value> = emojis.iter().map(|e| json!({
            "name": e.name, "id": e.id.get(), "animated": e.animated, "available": e.available,
        })).collect();
        Ok(json!({ "status": "success", "emojis": list, "count": list.len() }))
    }

    #[mcp_tool(description = "Get users currently in voice channels (requires active gateway)")]
    async fn get_voice_states(&self, guild_id: GuildId) -> Result<Value> {
        let cache = self.cache().context("gateway cache not available yet")?;
        let guild = cache.guild(guild_id.serenity()).context("guild not in cache")?;
        let mut voice_channels: HashMap<SerenityChannelId, Vec<Value>> = HashMap::new();
        for (user_id, vs) in &guild.voice_states {
            if let Some(ch_id) = vs.channel_id {
                voice_channels.entry(ch_id).or_default().push(json!({
                    "user_id": user_id.get(),
                    "self_mute": vs.self_mute, "self_deaf": vs.self_deaf,
                    "mute": vs.mute, "deaf": vs.deaf,
                }));
            }
        }
        let states: Vec<Value> = voice_channels.into_iter().map(|(ch_id, members)| {
            let ch_name = guild.channels.get(&ch_id).map(|c| c.name.clone()).unwrap_or_default();
            json!({ "channel_name": ch_name, "channel_id": ch_id.get(), "members": members, "member_count": members.len() })
        }).collect();
        let total: usize = states.iter().filter_map(|s| s["member_count"].as_u64()).sum::<u64>() as usize;
        Ok(json!({ "status": "success", "voice_states": states, "total_voice_users": total }))
    }

    // -- Analytics --

    #[mcp_tool(description = "Get message statistics for a channel over a time period")]
    async fn get_message_stats(
        &self,
        channel_id: ChannelId,
        #[describe("Time period in hours (default 24)")] hours: Option<u64>,
    ) -> Result<Value> {
        let hours = hours.unwrap_or(24);
        let messages = fetch_messages_since(self.http(), channel_id.serenity(), snowflake_hours_ago(hours), 10_000).await?;
        let mut authors = std::collections::HashSet::new();
        let (mut reactions, mut attachments, mut embeds) = (0u64, 0u64, 0u64);
        for msg in &messages {
            authors.insert(msg.author.id);
            reactions += msg.reactions.iter().map(|r| r.count).sum::<u64>();
            attachments += msg.attachments.len() as u64;
            embeds += msg.embeds.len() as u64;
        }
        Ok(json!({ "status": "success", "stats": {
            "time_period_hours": hours, "total_messages": messages.len(),
            "unique_authors": authors.len(), "reactions": reactions,
            "attachments": attachments, "embeds": embeds,
            "messages_per_hour": if hours > 0 { messages.len() as f64 / hours as f64 } else { 0.0 },
        }}))
    }

    #[mcp_tool(description = "Get the most active hours for a channel")]
    async fn get_channel_peak_hours(
        &self,
        channel_id: ChannelId,
        #[describe("Time period in days (default 7)")] days: Option<u64>,
    ) -> Result<Value> {
        let days = days.unwrap_or(7);
        let messages = fetch_messages_since(self.http(), channel_id.serenity(), snowflake_hours_ago(days * 24), 50_000).await?;
        let mut hourly: HashMap<u32, u64> = HashMap::new();
        let mut daily: HashMap<String, u64> = HashMap::new();
        for msg in &messages {
            let ts = msg.timestamp;
            let hour = (ts.unix_timestamp() % 86400 / 3600) as u32;
            let weekday = match (ts.unix_timestamp() / 86400 + 4) % 7 {
                0 => "Sunday", 1 => "Monday", 2 => "Tuesday", 3 => "Wednesday",
                4 => "Thursday", 5 => "Friday", _ => "Saturday",
            };
            *hourly.entry(hour).or_default() += 1;
            *daily.entry(weekday.to_string()).or_default() += 1;
        }
        let mut hourly_stats: Vec<Value> = hourly.iter()
            .map(|(&h, &c)| json!({"hour": h, "messages": c})).collect();
        hourly_stats.sort_by_key(|v| v["hour"].as_u64().unwrap_or(0));
        let avg = if days > 0 { messages.len() as f64 / (24.0 * days as f64) } else { 0.0 };
        let peak_hours: Vec<u32> = hourly.iter()
            .filter(|(_, &count)| (count as f64 / days as f64) > avg)
            .map(|(&hour, _)| hour).collect();
        Ok(json!({ "status": "success", "stats": {
            "time_period_days": days, "total_messages": messages.len(),
            "hourly_activity": hourly_stats, "daily_activity": daily, "peak_hours": peak_hours,
        }}))
    }

    #[mcp_tool(description = "Get trending messages and reactions in a guild")]
    async fn get_trending_content(
        &self,
        guild_id: GuildId,
        #[describe("Time period in hours (default 24)")] hours: Option<u64>,
        #[describe("Minimum reactions to count as trending (default 1)")] min_reactions: Option<u64>,
    ) -> Result<Value> {
        let cache = self.cache().context("gateway cache not available yet")?;
        let guild_ref = cache.guild(guild_id.serenity()).context("guild not in cache")?;
        let text_channels: Vec<SerenityChannelId> = guild_ref.channels.values()
            .filter(|ch| ch.kind == serenity::model::channel::ChannelType::Text)
            .map(|ch| ch.id).collect();
        drop(guild_ref);

        let hours = hours.unwrap_or(24);
        let min_reactions = min_reactions.unwrap_or(1);
        let after = snowflake_hours_ago(hours);
        let mut trending = Vec::new();
        let mut emoji_counts: HashMap<String, u64> = HashMap::new();
        for ch_id in text_channels {
            let messages = fetch_messages_since(self.http(), ch_id, after, 1000).await.unwrap_or_default();
            for msg in &messages {
                let total: u64 = msg.reactions.iter().map(|r| r.count).sum();
                for r in &msg.reactions {
                    *emoji_counts.entry(r.reaction_type.to_string()).or_default() += r.count;
                }
                if total >= min_reactions {
                    trending.push(json!({
                        "content": if msg.content.len() > 200 { format!("{}...", &msg.content[..197]) } else { msg.content.clone() },
                        "author": msg.author.name, "channel_id": msg.channel_id.get(),
                        "reactions": total, "timestamp": msg.timestamp.to_string(),
                    }));
                }
            }
        }
        trending.sort_by(|a, b| b["reactions"].as_u64().cmp(&a["reactions"].as_u64()));
        trending.truncate(10);
        let mut popular_emojis: Vec<Value> = emoji_counts.iter()
            .map(|(e, c)| json!({"emoji": e, "count": c})).collect();
        popular_emojis.sort_by(|a, b| b["count"].as_u64().cmp(&a["count"].as_u64()));
        popular_emojis.truncate(10);
        Ok(json!({ "status": "success", "trending": {
            "time_period_hours": hours, "messages": trending,
            "popular_emojis": popular_emojis, "total_trending_messages": trending.len(),
        }}))
    }

    #[mcp_tool(description = "Get active threads in a guild")]
    async fn get_active_threads(&self, guild_id: GuildId) -> Result<Value> {
        let threads_data = guild_id.serenity().get_active_threads(self.http()).await?;
        let threads: Vec<Value> = threads_data.threads.iter().map(|t| json!({
            "name": t.name, "id": t.id.get(),
            "parent_id": t.parent_id.map(|p| p.get()),
            "member_count": t.member_count, "message_count": t.message_count,
            "owner_id": t.owner_id.map(|o| o.get()),
        })).collect();
        Ok(json!({ "status": "success", "threads": threads, "count": threads.len() }))
    }

    #[mcp_tool(description = "Get activity statistics for a specific user in a guild")]
    async fn get_user_activity(
        &self,
        guild_id: GuildId,
        user_id: UserId,
        #[describe("Time period in days (default 7)")] days: Option<u64>,
    ) -> Result<Value> {
        let cache = self.cache().context("gateway cache not available yet")?;
        let guild_ref = cache.guild(guild_id.serenity()).context("guild not in cache")?;
        let text_channels: Vec<SerenityChannelId> = guild_ref.channels.values()
            .filter(|ch| ch.kind == serenity::model::channel::ChannelType::Text)
            .map(|ch| ch.id).collect();
        let member_name = guild_ref.members
            .get(&user_id.serenity())
            .map(|m| m.display_name().to_string())
            .unwrap_or_else(|| format!("User {}", user_id.0));
        drop(guild_ref);

        let days = days.unwrap_or(7);
        let after = snowflake_hours_ago(days * 24);
        let target = user_id.serenity();
        let mut total_messages: u64 = 0;
        let mut channel_activity: HashMap<String, u64> = HashMap::new();
        for ch_id in text_channels {
            let messages = fetch_messages_since(self.http(), ch_id, after, 5000).await.unwrap_or_default();
            let count = messages.iter().filter(|m| m.author.id == target).count() as u64;
            if count > 0 {
                let ch_name = self.cache()
                    .and_then(|c| c.guild(guild_id.serenity()))
                    .and_then(|g| g.channels.get(&ch_id).map(|c| c.name.clone()))
                    .unwrap_or_else(|| ch_id.get().to_string());
                channel_activity.insert(ch_name, count);
                total_messages += count;
            }
        }
        Ok(json!({ "status": "success", "activity": {
            "user_name": member_name, "time_period_days": days,
            "total_messages": total_messages,
            "messages_per_day": if days > 0 { total_messages as f64 / days as f64 } else { 0.0 },
            "channel_activity": channel_activity,
        }}))
    }
}
