//! Discord MCP tool handlers — annotated with rmcp's `#[tool]`.
//!
//! Tool definitions, dispatch, and argument deserialization are all
//! generated by rmcp's macros from the function signatures and param structs.

use super::DiscordSkill;
use super::param::*;
use anyhow::Context as _;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::tool;
use simply_daemon_api::skill_router;
use schemars::JsonSchema;
use serde::Deserialize;
use serde_json::json;
use serenity::builder::{CreateEmbed, CreateMessage, GetMessages};
use serenity::model::id::ChannelId as SerenityChannelId;
use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const DISCORD_EPOCH_MS: u64 = 1_420_070_400_000;

fn snowflake_hours_ago(hours: u64) -> serenity::model::id::MessageId {
    let now_ms = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_millis() as u64;
    let target_ms = now_ms.saturating_sub(hours * 3_600_000);
    serenity::model::id::MessageId::new((target_ms.saturating_sub(DISCORD_EPOCH_MS)) << 22)
}

async fn fetch_messages_since(
    http: &serenity::http::Http,
    channel_id: SerenityChannelId,
    after: serenity::model::id::MessageId,
    max: usize,
) -> anyhow::Result<Vec<serenity::model::channel::Message>> {
    let mut all = Vec::new();
    let mut cursor = after;
    loop {
        let batch = channel_id
            .messages(http, GetMessages::new().after(cursor).limit(100))
            .await?;
        if batch.is_empty() { break; }
        cursor = batch.iter().map(|m| m.id).max().unwrap_or(cursor);
        all.extend(batch);
        if all.len() >= max { all.truncate(max); break; }
    }
    Ok(all)
}

fn build_embed(title: Option<&str>, desc: Option<&str>, color: Option<&str>) -> Option<CreateEmbed> {
    if title.is_none() && desc.is_none() { return None; }
    let mut embed = CreateEmbed::new();
    if let Some(t) = title { embed = embed.title(t); }
    if let Some(d) = desc { embed = embed.description(d); }
    if let Some(hex) = color {
        if let Ok(c) = u32::from_str_radix(hex.trim_start_matches('#'), 16) {
            embed = embed.color(c);
        }
    }
    Some(embed)
}

fn message_to_json(msg: &serenity::model::channel::Message) -> serde_json::Value {
    let mut m = serde_json::Map::new();

    m.insert("name".into(), format!("<@{}>", msg.author.id.get()).into());
    // Discord timestamp format: <t:unix:R> for relative, <t:unix:f> for full
    let unix = msg.timestamp.unix_timestamp();
    m.insert("timestamp".into(), format!("<t:{unix}:R>").into());

    // Only include content if non-empty
    if !msg.content.is_empty() {
        m.insert("content".into(), msg.content.clone().into());
    }

    // Summarize embeds
    if !msg.embeds.is_empty() {
        let embed_summaries: Vec<serde_json::Value> = msg.embeds.iter().map(|e| {
            let mut parts = Vec::new();
            if let Some(ref t) = e.title { parts.push(t.clone()); }
            if let Some(ref d) = e.description {
                let truncated = if d.len() > 100 { format!("{}...", &d[..97]) } else { d.clone() };
                parts.push(truncated);
            }
            parts.join(": ").into()
        }).collect();
        m.insert("embeds".into(), embed_summaries.into());
    }

    // Summarize attachments
    if !msg.attachments.is_empty() {
        let att_names: Vec<serde_json::Value> = msg.attachments.iter()
            .map(|a| a.filename.clone().into())
            .collect();
        m.insert("attachments".into(), att_names.into());
    }

    // Only include reactions if any
    if !msg.reactions.is_empty() {
        let reactions: Vec<serde_json::Value> = msg.reactions.iter()
            .map(|r| format!("{} x{}", r.reaction_type, r.count).into())
            .collect();
        m.insert("reactions".into(), reactions.into());
    }

    m.into()
}

const NUMBER_EMOJIS: &[&str] = &["1️⃣", "2️⃣", "3️⃣", "4️⃣", "5️⃣", "6️⃣", "7️⃣", "8️⃣", "9️⃣", "🔟"];

// ---------------------------------------------------------------------------
// Parameter structs — JsonSchema provides automatic MCP tool schemas
// ---------------------------------------------------------------------------

#[derive(Deserialize, JsonSchema)]
pub struct SendMessageParams {
    pub channel_id: ChannelId,
    /// Message content
    pub content: String,
    /// Optional embed title
    pub embed_title: Option<String>,
    /// Optional embed description
    pub embed_description: Option<String>,
    /// Hex color code (e.g. #FF0000)
    pub embed_color: Option<String>,
}

#[derive(Deserialize, JsonSchema)]
pub struct ReplyToMessageParams {
    pub channel_id: ChannelId,
    pub message_id: MessageId,
    /// Reply content
    pub content: String,
    /// Mention the original author (default true)
    pub mention_author: Option<bool>,
    /// Optional embed title
    pub embed_title: Option<String>,
    /// Optional embed description
    pub embed_description: Option<String>,
    /// Hex color code
    pub embed_color: Option<String>,
}

#[derive(Deserialize, JsonSchema)]
pub struct CreateEmbedParams {
    pub channel_id: ChannelId,
    /// Embed title
    pub title: String,
    /// Embed description
    pub description: String,
    /// Field names
    pub fields_names: Option<Vec<String>>,
    /// Field values
    pub fields_values: Option<Vec<String>>,
}

#[derive(Deserialize, JsonSchema)]
pub struct CreatePollParams {
    pub channel_id: ChannelId,
    /// Poll question
    pub question: String,
    /// Poll options (max 10)
    pub options: Vec<String>,
    /// Custom emojis for options
    pub emojis: Option<Vec<String>>,
}

#[derive(Deserialize, JsonSchema)]
pub struct ChannelHistoryParams {
    pub channel_id: ChannelId,
    /// Max messages to fetch (default 100, max 1000)
    pub limit: Option<u64>,
}

#[derive(Deserialize, JsonSchema)]
pub struct SearchMessagesParams {
    pub channel_id: ChannelId,
    /// Text to search for (case-insensitive)
    pub query: String,
    /// Max messages to scan (default 100)
    pub limit: Option<u64>,
}

#[derive(Deserialize, JsonSchema)]
pub struct GuildIdParams {
    pub guild_id: GuildId,
}

#[derive(Deserialize, JsonSchema)]
pub struct JoinVoiceParams {
    pub guild_id: GuildId,
    /// Voice channel to join. If omitted, joins the first voice channel in the guild.
    pub voice_channel_id: Option<ChannelId>,
}

// ---------------------------------------------------------------------------
// Tool handlers — rmcp generates definitions + dispatch from these
// ---------------------------------------------------------------------------

#[skill_router(name = "discord")]
impl DiscordSkill {

    // -- Messaging --

    /// Send a message to a Discord channel
    #[tool(name = "send_message")]
    async fn send_message(&self, Parameters(p): Parameters<SendMessageParams>) -> String {
        match self.do_send_message(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// Reply to a specific message in a Discord channel
    #[tool(name = "reply_to_message")]
    async fn reply_to_message(&self, Parameters(p): Parameters<ReplyToMessageParams>) -> String {
        match self.do_reply_to_message(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// Send a rich embed message to a Discord channel
    #[tool(name = "create_embed")]
    async fn create_embed(&self, Parameters(p): Parameters<CreateEmbedParams>) -> String {
        match self.do_create_embed(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// Create a reaction-based poll in a Discord channel
    #[tool(name = "create_poll")]
    async fn create_poll(&self, Parameters(p): Parameters<CreatePollParams>) -> String {
        match self.do_create_poll(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    // -- Read --

    /// Get message history from a Discord channel
    #[tool(name = "get_channel_history")]
    async fn get_channel_history(&self, Parameters(p): Parameters<ChannelHistoryParams>) -> String {
        match self.do_get_channel_history(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// Search for messages in a channel containing specific text
    #[tool(name = "search_messages")]
    async fn search_messages(&self, Parameters(p): Parameters<SearchMessagesParams>) -> String {
        match self.do_search_messages(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// List all channels in a guild
    #[tool(name = "list_channels")]
    async fn list_channels(&self, Parameters(p): Parameters<GuildIdParams>) -> String {
        match self.do_list_channels(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// List all guilds the bot is in
    #[tool(name = "list_guilds")]
    async fn list_guilds(&self) -> String {
        match self.do_list_guilds().await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// Get custom emojis in a guild
    #[tool(name = "get_emoji_list")]
    async fn get_emoji_list(&self, Parameters(p): Parameters<GuildIdParams>) -> String {
        match self.do_get_emoji_list(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// Get users currently in voice channels (requires active gateway)
    #[tool(name = "get_voice_states")]
    async fn get_voice_states(&self, Parameters(p): Parameters<GuildIdParams>) -> String {
        match self.do_get_voice_states(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// Disconnect Lumina from a guild's voice channel, ending any active
    /// voice session (transcribe or listen).
    #[tool(name = "leave_voice")]
    async fn leave_voice(&self, Parameters(p): Parameters<GuildIdParams>) -> String {
        match self.do_leave_voice(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }
}

// ---------------------------------------------------------------------------
// Implementation methods — actual Discord API calls
// ---------------------------------------------------------------------------

impl DiscordSkill {
    async fn do_send_message(&self, p: SendMessageParams) -> anyhow::Result<serde_json::Value> {
        let ch = p.channel_id.serenity();
        let mut msg = CreateMessage::new().content(&p.content);
        if let Some(embed) = build_embed(p.embed_title.as_deref(), p.embed_description.as_deref(), p.embed_color.as_deref()) {
            msg = msg.embed(embed);
        }
        let sent = ch.send_message(self.http(), msg).await?;
        Ok(json!({ "status": "success", "message_id": sent.id.get().to_string(), "channel_id": sent.channel_id.get().to_string() }))
    }

    async fn do_reply_to_message(&self, p: ReplyToMessageParams) -> anyhow::Result<serde_json::Value> {
        let ch = p.channel_id.serenity();
        let ref_msg = ch.message(self.http(), p.message_id.serenity()).await?;
        let mut msg = CreateMessage::new().content(&p.content).reference_message(&ref_msg);
        if let Some(embed) = build_embed(p.embed_title.as_deref(), p.embed_description.as_deref(), p.embed_color.as_deref()) {
            msg = msg.embed(embed);
        }
        if p.mention_author == Some(false) {
            msg = msg.allowed_mentions(serenity::builder::CreateAllowedMentions::new().replied_user(false));
        }
        let sent = ch.send_message(self.http(), msg).await?;
        Ok(json!({ "status": "success", "message_id": sent.id.get().to_string() }))
    }

    async fn do_create_embed(&self, p: CreateEmbedParams) -> anyhow::Result<serde_json::Value> {
        let ch = p.channel_id.serenity();
        let mut embed = CreateEmbed::new().title(&p.title).description(&p.description).color(0x1ABC9C);
        if let (Some(names), Some(values)) = (&p.fields_names, &p.fields_values) {
            for (name, value) in names.iter().zip(values.iter()) {
                let v = if value.len() > 1024 { format!("{}...", &value[..1021]) } else { value.clone() };
                embed = embed.field(name, v, false);
            }
        }
        let sent = ch.send_message(self.http(), CreateMessage::new().embed(embed)).await?;
        Ok(json!({ "status": "success", "message_id": sent.id.get().to_string() }))
    }

    async fn do_create_poll(&self, p: CreatePollParams) -> anyhow::Result<serde_json::Value> {
        if p.options.len() > 10 { anyhow::bail!("maximum 10 poll options"); }
        let ch = p.channel_id.serenity();
        let emoji_list = p.emojis.as_deref().unwrap_or(&[]);
        let text: Vec<String> = p.options.iter().enumerate().map(|(i, opt)| {
            let e = emoji_list.get(i).map(|s| s.as_str()).unwrap_or(NUMBER_EMOJIS.get(i).copied().unwrap_or("▪️"));
            format!("{e} - {opt}")
        }).collect();
        let embed = CreateEmbed::new().title(format!("📋 Poll: {}", p.question)).description(text.join("\n")).color(0x3498DB);
        let sent = ch.send_message(self.http(), CreateMessage::new().embed(embed)).await?;
        for (i, _) in p.options.iter().enumerate() {
            let e = emoji_list.get(i).map(|s| s.as_str()).unwrap_or(NUMBER_EMOJIS.get(i).copied().unwrap_or("▪️"));
            sent.react(self.http(), serenity::model::channel::ReactionType::Unicode(e.to_string())).await?;
        }
        Ok(json!({ "status": "success", "message_id": sent.id.get().to_string(), "options_count": p.options.len() }))
    }

    async fn do_get_channel_history(&self, p: ChannelHistoryParams) -> anyhow::Result<serde_json::Value> {
        let ch = p.channel_id.serenity();
        let limit = p.limit.unwrap_or(100).min(1000);
        let mut all = Vec::new();
        let mut before: Option<serenity::model::id::MessageId> = None;
        let mut remaining = limit;
        while remaining > 0 {
            let batch_size = remaining.min(100) as u8;
            let mut req = GetMessages::new().limit(batch_size);
            if let Some(id) = before { req = req.before(id); }
            let batch = ch.messages(self.http(), req).await?;
            if batch.is_empty() { break; }
            before = batch.last().map(|m| m.id);
            remaining = remaining.saturating_sub(batch.len() as u64);
            all.extend(batch);
        }
        let messages: Vec<serde_json::Value> = all.iter().map(message_to_json).collect();
        Ok(messages.into())
    }

    async fn do_search_messages(&self, p: SearchMessagesParams) -> anyhow::Result<serde_json::Value> {
        let ch = p.channel_id.serenity();
        let limit = p.limit.unwrap_or(100).min(1000);
        let query_lower = p.query.to_lowercase();
        let mut before: Option<serenity::model::id::MessageId> = None;
        let mut remaining = limit;
        let mut matches = Vec::new();
        while remaining > 0 {
            let batch_size = remaining.min(100) as u8;
            let mut req = GetMessages::new().limit(batch_size);
            if let Some(id) = before { req = req.before(id); }
            let batch = ch.messages(self.http(), req).await?;
            if batch.is_empty() { break; }
            before = batch.last().map(|m| m.id);
            remaining = remaining.saturating_sub(batch.len() as u64);
            for msg in &batch {
                if msg.content.to_lowercase().contains(&query_lower) {
                    matches.push(message_to_json(msg));
                }
            }
        }
        Ok(matches.into())
    }

    async fn do_list_channels(&self, p: GuildIdParams) -> anyhow::Result<serde_json::Value> {
        use serenity::model::channel::ChannelType;
        let channels = p.guild_id.serenity().channels(self.http()).await?;
        let list: Vec<serde_json::Value> = channels.values()
            .filter(|ch| !matches!(ch.kind, ChannelType::Category))
            .map(|ch| {
                let category = ch.parent_id.and_then(|pid| channels.get(&pid).map(|c| c.name.clone()));
                json!({
                    "name": ch.name, "id": ch.id.get().to_string(),
                    "kind": format!("{:?}", ch.kind),
                    "category": category,
                })
            }).collect();
        Ok(list.into())
    }

    async fn do_list_guilds(&self) -> anyhow::Result<serde_json::Value> {
        let cache = self.cache().context("gateway cache not available yet")?;
        let guilds: Vec<serde_json::Value> = cache.guilds().iter().filter_map(|id| {
            cache.guild(*id).map(|g| json!({ "name": g.name.clone(), "id": id.get().to_string() }))
        }).collect();
        Ok(guilds.into())
    }

    async fn do_get_emoji_list(&self, p: GuildIdParams) -> anyhow::Result<serde_json::Value> {
        let emojis = p.guild_id.serenity().emojis(self.http()).await?;
        let list: Vec<serde_json::Value> = emojis.iter().map(|e| json!({
            "name": e.name, "id": e.id.get().to_string(), "animated": e.animated, "available": e.available,
        })).collect();
        Ok(list.into())
    }

    async fn do_leave_voice(&self, p: GuildIdParams) -> anyhow::Result<serde_json::Value> {
        let voice_mgr = self.voice_manager()
            .context("voice manager not initialized")?;
        let left = voice_mgr.leave_voice(p.guild_id.serenity()).await?;
        Ok(json!({
            "status": "success",
            "left": left,
            "message": if left { "Left voice channel." } else { "Not connected to voice in this guild." },
        }))
    }

    async fn do_get_voice_states(&self, p: GuildIdParams) -> anyhow::Result<serde_json::Value> {
        let cache = self.cache().context("gateway cache not available yet")?;
        let guild = cache.guild(p.guild_id.serenity()).context("guild not in cache")?;
        let mut voice_channels: HashMap<SerenityChannelId, Vec<serde_json::Value>> = HashMap::new();
        for (user_id, vs) in &guild.voice_states {
            if let Some(ch_id) = vs.channel_id {
                voice_channels.entry(ch_id).or_default().push(json!({
                    "user_id": user_id.get().to_string(), "self_mute": vs.self_mute, "self_deaf": vs.self_deaf,
                    "mute": vs.mute, "deaf": vs.deaf,
                }));
            }
        }
        let states: Vec<serde_json::Value> = voice_channels.into_iter().map(|(ch_id, members)| {
            let ch_name = guild.channels.get(&ch_id).map(|c| c.name.clone()).unwrap_or_default();
            json!({ "channel_name": ch_name, "channel_id": ch_id.get().to_string(), "members": members, "member_count": members.len() })
        }).collect();
        let total: usize = states.iter().filter_map(|s| s["member_count"].as_u64()).sum::<u64>() as usize;
        Ok(json!({ "status": "success", "voice_states": states, "total_voice_users": total }))
    }
}
