//! Discord MCP tool handlers — annotated with rmcp's `#[tool]`.
//!
//! Tool definitions, dispatch, and argument deserialization are all
//! generated by rmcp's macros from the function signatures and param structs.

use super::LuminaMcpServer;
use super::param::*;
use anyhow::Context as _;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::{tool, tool_router};
use schemars::JsonSchema;
use serde::Deserialize;
use serde_json::json;
use serenity::builder::{CreateEmbed, CreateMessage, GetMessages};
use serenity::model::id::ChannelId as SerenityChannelId;
use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const DISCORD_EPOCH_MS: u64 = 1_420_070_400_000;

fn snowflake_hours_ago(hours: u64) -> serenity::model::id::MessageId {
    let now_ms = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_millis() as u64;
    let target_ms = now_ms.saturating_sub(hours * 3_600_000);
    serenity::model::id::MessageId::new((target_ms.saturating_sub(DISCORD_EPOCH_MS)) << 22)
}

async fn fetch_messages_since(
    http: &serenity::http::Http,
    channel_id: SerenityChannelId,
    after: serenity::model::id::MessageId,
    max: usize,
) -> anyhow::Result<Vec<serenity::model::channel::Message>> {
    let mut all = Vec::new();
    let mut cursor = after;
    loop {
        let batch = channel_id
            .messages(http, GetMessages::new().after(cursor).limit(100))
            .await?;
        if batch.is_empty() { break; }
        cursor = batch.iter().map(|m| m.id).max().unwrap_or(cursor);
        all.extend(batch);
        if all.len() >= max { all.truncate(max); break; }
    }
    Ok(all)
}

fn build_embed(title: Option<&str>, desc: Option<&str>, color: Option<&str>) -> Option<CreateEmbed> {
    if title.is_none() && desc.is_none() { return None; }
    let mut embed = CreateEmbed::new();
    if let Some(t) = title { embed = embed.title(t); }
    if let Some(d) = desc { embed = embed.description(d); }
    if let Some(hex) = color {
        if let Ok(c) = u32::from_str_radix(hex.trim_start_matches('#'), 16) {
            embed = embed.color(c);
        }
    }
    Some(embed)
}

fn message_to_json(msg: &serenity::model::channel::Message) -> serde_json::Value {
    json!({
        "id": msg.id.get(), "channel_id": msg.channel_id.get(),
        "author": { "id": msg.author.id.get(), "name": msg.author.name },
        "content": msg.content, "timestamp": msg.timestamp.to_string(),
        "reactions": msg.reactions.iter().map(|r| json!({
            "emoji": r.reaction_type.to_string(), "count": r.count,
        })).collect::<Vec<_>>(),
        "attachments": msg.attachments.len(), "embeds": msg.embeds.len(),
    })
}

const NUMBER_EMOJIS: &[&str] = &["1️⃣", "2️⃣", "3️⃣", "4️⃣", "5️⃣", "6️⃣", "7️⃣", "8️⃣", "9️⃣", "🔟"];

// ---------------------------------------------------------------------------
// Parameter structs — JsonSchema provides automatic MCP tool schemas
// ---------------------------------------------------------------------------

#[derive(Deserialize, JsonSchema)]
pub struct SendMessageParams {
    pub channel_id: ChannelId,
    /// Message content
    pub content: String,
    /// Optional embed title
    pub embed_title: Option<String>,
    /// Optional embed description
    pub embed_description: Option<String>,
    /// Hex color code (e.g. #FF0000)
    pub embed_color: Option<String>,
}

#[derive(Deserialize, JsonSchema)]
pub struct ReplyToMessageParams {
    pub channel_id: ChannelId,
    pub message_id: MessageId,
    /// Reply content
    pub content: String,
    /// Mention the original author (default true)
    pub mention_author: Option<bool>,
    /// Optional embed title
    pub embed_title: Option<String>,
    /// Optional embed description
    pub embed_description: Option<String>,
    /// Hex color code
    pub embed_color: Option<String>,
}

#[derive(Deserialize, JsonSchema)]
pub struct CreateEmbedParams {
    pub channel_id: ChannelId,
    /// Embed title
    pub title: String,
    /// Embed description
    pub description: String,
    /// Field names
    pub fields_names: Option<Vec<String>>,
    /// Field values
    pub fields_values: Option<Vec<String>>,
}

#[derive(Deserialize, JsonSchema)]
pub struct CreatePollParams {
    pub channel_id: ChannelId,
    /// Poll question
    pub question: String,
    /// Poll options (max 10)
    pub options: Vec<String>,
    /// Custom emojis for options
    pub emojis: Option<Vec<String>>,
}

#[derive(Deserialize, JsonSchema)]
pub struct ChannelHistoryParams {
    pub channel_id: ChannelId,
    /// Max messages to fetch (default 100, max 1000)
    pub limit: Option<u64>,
}

#[derive(Deserialize, JsonSchema)]
pub struct SearchMessagesParams {
    pub channel_id: ChannelId,
    /// Text to search for (case-insensitive)
    pub query: String,
    /// Max messages to scan (default 100)
    pub limit: Option<u64>,
}

#[derive(Deserialize, JsonSchema)]
pub struct GuildIdParams {
    pub guild_id: GuildId,
}

#[derive(Deserialize, JsonSchema)]
pub struct ChannelStatsParams {
    pub channel_id: ChannelId,
    /// Time period in hours (default 24)
    pub hours: Option<u64>,
}

#[derive(Deserialize, JsonSchema)]
pub struct ChannelPeakParams {
    pub channel_id: ChannelId,
    /// Time period in days (default 7)
    pub days: Option<u64>,
}

#[derive(Deserialize, JsonSchema)]
pub struct TrendingParams {
    pub guild_id: GuildId,
    /// Time period in hours (default 24)
    pub hours: Option<u64>,
    /// Minimum reactions to count as trending (default 1)
    pub min_reactions: Option<u64>,
}

#[derive(Deserialize, JsonSchema)]
pub struct UserActivityParams {
    pub guild_id: GuildId,
    pub user_id: UserId,
    /// Time period in days (default 7)
    pub days: Option<u64>,
}

// ---------------------------------------------------------------------------
// Tool handlers — rmcp generates definitions + dispatch from these
// ---------------------------------------------------------------------------

#[tool_router(vis = "pub(crate)")]
impl LuminaMcpServer {

    // -- Messaging --

    /// Send a message to a Discord channel
    #[tool(name = "send_message")]
    async fn send_message(&self, Parameters(p): Parameters<SendMessageParams>) -> String {
        match self.do_send_message(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// Reply to a specific message in a Discord channel
    #[tool(name = "reply_to_message")]
    async fn reply_to_message(&self, Parameters(p): Parameters<ReplyToMessageParams>) -> String {
        match self.do_reply_to_message(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// Send a rich embed message to a Discord channel
    #[tool(name = "create_embed")]
    async fn create_embed(&self, Parameters(p): Parameters<CreateEmbedParams>) -> String {
        match self.do_create_embed(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// Create a reaction-based poll in a Discord channel
    #[tool(name = "create_poll")]
    async fn create_poll(&self, Parameters(p): Parameters<CreatePollParams>) -> String {
        match self.do_create_poll(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    // -- Read --

    /// Get message history from a Discord channel
    #[tool(name = "get_channel_history")]
    async fn get_channel_history(&self, Parameters(p): Parameters<ChannelHistoryParams>) -> String {
        match self.do_get_channel_history(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// Search for messages in a channel containing specific text
    #[tool(name = "search_messages")]
    async fn search_messages(&self, Parameters(p): Parameters<SearchMessagesParams>) -> String {
        match self.do_search_messages(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// List all channels in a guild
    #[tool(name = "list_channels")]
    async fn list_channels(&self, Parameters(p): Parameters<GuildIdParams>) -> String {
        match self.do_list_channels(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// List all guilds the bot is in
    #[tool(name = "list_guilds")]
    async fn list_guilds(&self) -> String {
        match self.do_list_guilds().await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// Get custom emojis in a guild
    #[tool(name = "get_emoji_list")]
    async fn get_emoji_list(&self, Parameters(p): Parameters<GuildIdParams>) -> String {
        match self.do_get_emoji_list(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// Get users currently in voice channels (requires active gateway)
    #[tool(name = "get_voice_states")]
    async fn get_voice_states(&self, Parameters(p): Parameters<GuildIdParams>) -> String {
        match self.do_get_voice_states(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    // -- Analytics --

    /// Get message statistics for a channel over a time period
    #[tool(name = "get_message_stats")]
    async fn get_message_stats(&self, Parameters(p): Parameters<ChannelStatsParams>) -> String {
        match self.do_get_message_stats(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// Get the most active hours for a channel
    #[tool(name = "get_channel_peak_hours")]
    async fn get_channel_peak_hours(&self, Parameters(p): Parameters<ChannelPeakParams>) -> String {
        match self.do_get_channel_peak_hours(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// Get trending messages and reactions in a guild
    #[tool(name = "get_trending_content")]
    async fn get_trending_content(&self, Parameters(p): Parameters<TrendingParams>) -> String {
        match self.do_get_trending_content(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// Get active threads in a guild
    #[tool(name = "get_active_threads")]
    async fn get_active_threads(&self, Parameters(p): Parameters<GuildIdParams>) -> String {
        match self.do_get_active_threads(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }

    /// Get activity statistics for a specific user in a guild
    #[tool(name = "get_user_activity")]
    async fn get_user_activity(&self, Parameters(p): Parameters<UserActivityParams>) -> String {
        match self.do_get_user_activity(p).await {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap(),
            Err(e) => format!("Error: {e}"),
        }
    }
}

// ---------------------------------------------------------------------------
// Implementation methods — actual Discord API calls
// ---------------------------------------------------------------------------

impl LuminaMcpServer {
    async fn do_send_message(&self, p: SendMessageParams) -> anyhow::Result<serde_json::Value> {
        let ch = p.channel_id.serenity();
        let mut msg = CreateMessage::new().content(&p.content);
        if let Some(embed) = build_embed(p.embed_title.as_deref(), p.embed_description.as_deref(), p.embed_color.as_deref()) {
            msg = msg.embed(embed);
        }
        let sent = ch.send_message(self.http(), msg).await?;
        Ok(json!({ "status": "success", "message_id": sent.id.get(), "channel_id": sent.channel_id.get() }))
    }

    async fn do_reply_to_message(&self, p: ReplyToMessageParams) -> anyhow::Result<serde_json::Value> {
        let ch = p.channel_id.serenity();
        let ref_msg = ch.message(self.http(), p.message_id.serenity()).await?;
        let mut msg = CreateMessage::new().content(&p.content).reference_message(&ref_msg);
        if let Some(embed) = build_embed(p.embed_title.as_deref(), p.embed_description.as_deref(), p.embed_color.as_deref()) {
            msg = msg.embed(embed);
        }
        if p.mention_author == Some(false) {
            msg = msg.allowed_mentions(serenity::builder::CreateAllowedMentions::new().replied_user(false));
        }
        let sent = ch.send_message(self.http(), msg).await?;
        Ok(json!({ "status": "success", "message_id": sent.id.get() }))
    }

    async fn do_create_embed(&self, p: CreateEmbedParams) -> anyhow::Result<serde_json::Value> {
        let ch = p.channel_id.serenity();
        let mut embed = CreateEmbed::new().title(&p.title).description(&p.description).color(0x1ABC9C);
        if let (Some(names), Some(values)) = (&p.fields_names, &p.fields_values) {
            for (name, value) in names.iter().zip(values.iter()) {
                let v = if value.len() > 1024 { format!("{}...", &value[..1021]) } else { value.clone() };
                embed = embed.field(name, v, false);
            }
        }
        let sent = ch.send_message(self.http(), CreateMessage::new().embed(embed)).await?;
        Ok(json!({ "status": "success", "message_id": sent.id.get() }))
    }

    async fn do_create_poll(&self, p: CreatePollParams) -> anyhow::Result<serde_json::Value> {
        if p.options.len() > 10 { anyhow::bail!("maximum 10 poll options"); }
        let ch = p.channel_id.serenity();
        let emoji_list = p.emojis.as_deref().unwrap_or(&[]);
        let text: Vec<String> = p.options.iter().enumerate().map(|(i, opt)| {
            let e = emoji_list.get(i).map(|s| s.as_str()).unwrap_or(NUMBER_EMOJIS.get(i).copied().unwrap_or("▪️"));
            format!("{e} - {opt}")
        }).collect();
        let embed = CreateEmbed::new().title(format!("📋 Poll: {}", p.question)).description(text.join("\n")).color(0x3498DB);
        let sent = ch.send_message(self.http(), CreateMessage::new().embed(embed)).await?;
        for (i, _) in p.options.iter().enumerate() {
            let e = emoji_list.get(i).map(|s| s.as_str()).unwrap_or(NUMBER_EMOJIS.get(i).copied().unwrap_or("▪️"));
            sent.react(self.http(), serenity::model::channel::ReactionType::Unicode(e.to_string())).await?;
        }
        Ok(json!({ "status": "success", "message_id": sent.id.get(), "options_count": p.options.len() }))
    }

    async fn do_get_channel_history(&self, p: ChannelHistoryParams) -> anyhow::Result<serde_json::Value> {
        let ch = p.channel_id.serenity();
        let limit = p.limit.unwrap_or(100).min(1000);
        let mut all = Vec::new();
        let mut before: Option<serenity::model::id::MessageId> = None;
        let mut remaining = limit;
        while remaining > 0 {
            let batch_size = remaining.min(100) as u8;
            let mut req = GetMessages::new().limit(batch_size);
            if let Some(id) = before { req = req.before(id); }
            let batch = ch.messages(self.http(), req).await?;
            if batch.is_empty() { break; }
            before = batch.last().map(|m| m.id);
            remaining = remaining.saturating_sub(batch.len() as u64);
            all.extend(batch);
        }
        let messages: Vec<serde_json::Value> = all.iter().map(message_to_json).collect();
        Ok(json!({ "status": "success", "messages": messages, "count": messages.len() }))
    }

    async fn do_search_messages(&self, p: SearchMessagesParams) -> anyhow::Result<serde_json::Value> {
        let ch = p.channel_id.serenity();
        let limit = p.limit.unwrap_or(100).min(1000);
        let query_lower = p.query.to_lowercase();
        let mut before: Option<serenity::model::id::MessageId> = None;
        let mut remaining = limit;
        let mut matches = Vec::new();
        while remaining > 0 {
            let batch_size = remaining.min(100) as u8;
            let mut req = GetMessages::new().limit(batch_size);
            if let Some(id) = before { req = req.before(id); }
            let batch = ch.messages(self.http(), req).await?;
            if batch.is_empty() { break; }
            before = batch.last().map(|m| m.id);
            remaining = remaining.saturating_sub(batch.len() as u64);
            for msg in &batch {
                if msg.content.to_lowercase().contains(&query_lower) {
                    matches.push(message_to_json(msg));
                }
            }
        }
        Ok(json!({ "status": "success", "messages": matches, "count": matches.len() }))
    }

    async fn do_list_channels(&self, p: GuildIdParams) -> anyhow::Result<serde_json::Value> {
        use serenity::model::channel::ChannelType;
        let channels = p.guild_id.serenity().channels(self.http()).await?;
        let list: Vec<serde_json::Value> = channels.values()
            .filter(|ch| !matches!(ch.kind, ChannelType::Category))
            .map(|ch| {
                let category = ch.parent_id.and_then(|pid| channels.get(&pid).map(|c| c.name.clone()));
                json!({
                    "name": ch.name, "id": ch.id.get().to_string(),
                    "kind": format!("{:?}", ch.kind),
                    "category": category,
                })
            }).collect();
        Ok(json!({ "status": "success", "channels": list, "count": list.len() }))
    }

    async fn do_list_guilds(&self) -> anyhow::Result<serde_json::Value> {
        let cache = self.cache().context("gateway cache not available yet")?;
        let guilds: Vec<serde_json::Value> = cache.guilds().iter().filter_map(|id| {
            cache.guild(*id).map(|g| json!({ "name": g.name.clone(), "id": id.get() }))
        }).collect();
        Ok(json!({ "status": "success", "guilds": guilds, "count": guilds.len() }))
    }

    async fn do_get_emoji_list(&self, p: GuildIdParams) -> anyhow::Result<serde_json::Value> {
        let emojis = p.guild_id.serenity().emojis(self.http()).await?;
        let list: Vec<serde_json::Value> = emojis.iter().map(|e| json!({
            "name": e.name, "id": e.id.get(), "animated": e.animated, "available": e.available,
        })).collect();
        Ok(json!({ "status": "success", "emojis": list, "count": list.len() }))
    }

    async fn do_get_voice_states(&self, p: GuildIdParams) -> anyhow::Result<serde_json::Value> {
        let cache = self.cache().context("gateway cache not available yet")?;
        let guild = cache.guild(p.guild_id.serenity()).context("guild not in cache")?;
        let mut voice_channels: HashMap<SerenityChannelId, Vec<serde_json::Value>> = HashMap::new();
        for (user_id, vs) in &guild.voice_states {
            if let Some(ch_id) = vs.channel_id {
                voice_channels.entry(ch_id).or_default().push(json!({
                    "user_id": user_id.get(), "self_mute": vs.self_mute, "self_deaf": vs.self_deaf,
                    "mute": vs.mute, "deaf": vs.deaf,
                }));
            }
        }
        let states: Vec<serde_json::Value> = voice_channels.into_iter().map(|(ch_id, members)| {
            let ch_name = guild.channels.get(&ch_id).map(|c| c.name.clone()).unwrap_or_default();
            json!({ "channel_name": ch_name, "channel_id": ch_id.get(), "members": members, "member_count": members.len() })
        }).collect();
        let total: usize = states.iter().filter_map(|s| s["member_count"].as_u64()).sum::<u64>() as usize;
        Ok(json!({ "status": "success", "voice_states": states, "total_voice_users": total }))
    }

    async fn do_get_message_stats(&self, p: ChannelStatsParams) -> anyhow::Result<serde_json::Value> {
        let hours = p.hours.unwrap_or(24);
        let messages = fetch_messages_since(self.http(), p.channel_id.serenity(), snowflake_hours_ago(hours), 10_000).await?;
        let mut authors = std::collections::HashSet::new();
        let (mut reactions, mut attachments, mut embeds) = (0u64, 0u64, 0u64);
        for msg in &messages {
            authors.insert(msg.author.id);
            reactions += msg.reactions.iter().map(|r| r.count).sum::<u64>();
            attachments += msg.attachments.len() as u64;
            embeds += msg.embeds.len() as u64;
        }
        Ok(json!({ "status": "success", "stats": {
            "time_period_hours": hours, "total_messages": messages.len(),
            "unique_authors": authors.len(), "reactions": reactions,
            "attachments": attachments, "embeds": embeds,
            "messages_per_hour": if hours > 0 { messages.len() as f64 / hours as f64 } else { 0.0 },
        }}))
    }

    async fn do_get_channel_peak_hours(&self, p: ChannelPeakParams) -> anyhow::Result<serde_json::Value> {
        let days = p.days.unwrap_or(7);
        let messages = fetch_messages_since(self.http(), p.channel_id.serenity(), snowflake_hours_ago(days * 24), 50_000).await?;
        let mut hourly: HashMap<u32, u64> = HashMap::new();
        let mut daily: HashMap<String, u64> = HashMap::new();
        for msg in &messages {
            let ts = msg.timestamp;
            let hour = (ts.unix_timestamp() % 86400 / 3600) as u32;
            let weekday = match (ts.unix_timestamp() / 86400 + 4) % 7 {
                0 => "Sunday", 1 => "Monday", 2 => "Tuesday", 3 => "Wednesday",
                4 => "Thursday", 5 => "Friday", _ => "Saturday",
            };
            *hourly.entry(hour).or_default() += 1;
            *daily.entry(weekday.to_string()).or_default() += 1;
        }
        let mut hourly_stats: Vec<serde_json::Value> = hourly.iter()
            .map(|(&h, &c)| json!({"hour": h, "messages": c})).collect();
        hourly_stats.sort_by_key(|v| v["hour"].as_u64().unwrap_or(0));
        let avg = if days > 0 { messages.len() as f64 / (24.0 * days as f64) } else { 0.0 };
        let peak_hours: Vec<u32> = hourly.iter()
            .filter(|(_, &count)| (count as f64 / days as f64) > avg)
            .map(|(&hour, _)| hour).collect();
        Ok(json!({ "status": "success", "stats": {
            "time_period_days": days, "total_messages": messages.len(),
            "hourly_activity": hourly_stats, "daily_activity": daily, "peak_hours": peak_hours,
        }}))
    }

    async fn do_get_trending_content(&self, p: TrendingParams) -> anyhow::Result<serde_json::Value> {
        let text_channels: Vec<SerenityChannelId> = {
            let cache = self.cache().context("gateway cache not available yet")?;
            let guild_ref = cache.guild(p.guild_id.serenity()).context("guild not in cache")?;
            guild_ref.channels.values()
                .filter(|ch| ch.kind == serenity::model::channel::ChannelType::Text)
                .map(|ch| ch.id).collect()
        };
        let hours = p.hours.unwrap_or(24);
        let min_reactions = p.min_reactions.unwrap_or(1);
        let after = snowflake_hours_ago(hours);
        let mut trending = Vec::new();
        let mut emoji_counts: HashMap<String, u64> = HashMap::new();
        for ch_id in text_channels {
            let messages = fetch_messages_since(self.http(), ch_id, after, 1000).await.unwrap_or_default();
            for msg in &messages {
                let total: u64 = msg.reactions.iter().map(|r| r.count).sum();
                for r in &msg.reactions { *emoji_counts.entry(r.reaction_type.to_string()).or_default() += r.count; }
                if total >= min_reactions {
                    trending.push(json!({
                        "content": if msg.content.len() > 200 { format!("{}...", &msg.content[..197]) } else { msg.content.clone() },
                        "author": msg.author.name, "channel_id": msg.channel_id.get(),
                        "reactions": total, "timestamp": msg.timestamp.to_string(),
                    }));
                }
            }
        }
        trending.sort_by(|a, b| b["reactions"].as_u64().cmp(&a["reactions"].as_u64()));
        trending.truncate(10);
        let mut popular_emojis: Vec<serde_json::Value> = emoji_counts.iter()
            .map(|(e, c)| json!({"emoji": e, "count": c})).collect();
        popular_emojis.sort_by(|a, b| b["count"].as_u64().cmp(&a["count"].as_u64()));
        popular_emojis.truncate(10);
        Ok(json!({ "status": "success", "trending": {
            "time_period_hours": hours, "messages": trending,
            "popular_emojis": popular_emojis, "total_trending_messages": trending.len(),
        }}))
    }

    async fn do_get_active_threads(&self, p: GuildIdParams) -> anyhow::Result<serde_json::Value> {
        let threads_data = p.guild_id.serenity().get_active_threads(self.http()).await?;
        let threads: Vec<serde_json::Value> = threads_data.threads.iter().map(|t| json!({
            "name": t.name, "id": t.id.get(), "parent_id": t.parent_id.map(|p| p.get()),
            "member_count": t.member_count, "message_count": t.message_count,
            "owner_id": t.owner_id.map(|o| o.get()),
        })).collect();
        Ok(json!({ "status": "success", "threads": threads, "count": threads.len() }))
    }

    async fn do_get_user_activity(&self, p: UserActivityParams) -> anyhow::Result<serde_json::Value> {
        let (text_channels, member_name) = {
            let cache = self.cache().context("gateway cache not available yet")?;
            let guild_ref = cache.guild(p.guild_id.serenity()).context("guild not in cache")?;
            let channels: Vec<SerenityChannelId> = guild_ref.channels.values()
                .filter(|ch| ch.kind == serenity::model::channel::ChannelType::Text)
                .map(|ch| ch.id).collect();
            let name = guild_ref.members.get(&p.user_id.serenity())
                .map(|m| m.display_name().to_string())
                .unwrap_or_else(|| format!("User {}", p.user_id.0));
            (channels, name)
        };
        let days = p.days.unwrap_or(7);
        let after = snowflake_hours_ago(days * 24);
        let target = p.user_id.serenity();
        let mut total_messages: u64 = 0;
        let mut channel_activity: HashMap<String, u64> = HashMap::new();
        for ch_id in text_channels {
            let messages = fetch_messages_since(self.http(), ch_id, after, 5000).await.unwrap_or_default();
            let count = messages.iter().filter(|m| m.author.id == target).count() as u64;
            if count > 0 {
                let ch_name = self.cache()
                    .and_then(|c| c.guild(p.guild_id.serenity()))
                    .and_then(|g| g.channels.get(&ch_id).map(|c| c.name.clone()))
                    .unwrap_or_else(|| ch_id.get().to_string());
                channel_activity.insert(ch_name, count);
                total_messages += count;
            }
        }
        Ok(json!({ "status": "success", "activity": {
            "user_name": member_name, "time_period_days": days,
            "total_messages": total_messages,
            "messages_per_day": if days > 0 { total_messages as f64 / days as f64 } else { 0.0 },
            "channel_activity": channel_activity,
        }}))
    }
}
